In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
DF_Compras = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\NewStudy_04-10\\RAW_COMPRAS_ENTRADAS.csv")

In [3]:
DF_Compras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO
0,NF-1006,01/01/2026,CEASA SP - PRODUTORES UNIDOS,101,55,163.39,Mateus
1,NF-1046,01/01/2026,CEASA SP - PRODUTORES UNIDOS,102,119,335.78,Thiago
2,NF-1018,01/01/2026,CEASA SP - PRODUTORES UNIDOS,103,115 KG,243.92,Thiago
3,NF-1013,01/01/2026,CEASA SP - PRODUTORES UNIDOS,104,41,123.78,diego
4,NF-1004,01/01/2026,CEASA SP - PRODUTORES UNIDOS,105,85,235.48,Diego

-----

In [4]:
silverCompras = DF_Compras # Instancia tabela compras

In [5]:
silverCompras['COD_PROD'] = silverCompras['COD_PROD'].fillna(1000001) # Trata valores nulos com 1000001
silverCompras['COD_PROD'].replace(0.0, 1000001 ) # trata 0 para 1000001
silverCompras['COD_PROD'].value_counts()

COD_PROD
101    51
102    49
104    48
103    47
105    47
203    41
204    41
201    39
202    39
Name: count, dtype: int64

In [6]:
silverCompras['N_NF'] = silverCompras['NUM_NOTA_FISCAL'].str.replace('NF-','')

In [7]:
silverCompras['FORNECEDOR'].value_counts()

FORNECEDOR
CEASA SP - PRODUTORES UNIDOS     242
FRIGORIFICO FRIBOI / BOI LEVE    160
Name: count, dtype: int64

In [8]:
silverCompras['FORNECEDOR'] = (
    silverCompras['FORNECEDOR']
    .str.replace(' - PRODUTORES UNIDOS','')
    .str.replace(' / BOI LEVE','')
)

In [9]:
silverCompras['FORNECEDOR'].value_counts()

FORNECEDOR
CEASA SP              242
FRIGORIFICO FRIBOI    160
Name: count, dtype: int64

In [10]:
silverCompras['QTD_COMPRADA'] = silverCompras['QTD_COMPRADA'].str.replace('KG','')

In [11]:
silverCompras['VALOR_TOTAL_NOTA'] = silverCompras['VALOR_TOTAL_NOTA'].str.replace(',','.')

In [12]:
silverCompras['TOTAL_NOTA'] = pd.to_numeric(silverCompras['VALOR_TOTAL_NOTA'], errors="coerce")

-----

In [13]:
silverCompras['RESPONSAVEL_RECEBIMENTO'] = silverCompras['RESPONSAVEL_RECEBIMENTO'].str.upper()

In [14]:
silverCompras['DATA'] = pd.to_datetime(silverCompras['DATA_ENTRADA'], format='%d/%m/%Y')

silverCompras['MES'] = silverCompras['DATA'].dt.month
silverCompras['ANO'] = silverCompras['DATA'].dt.year

In [15]:

DF_Compras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO,N_NF,TOTAL_NOTA,DATA,MES,ANO
0,NF-1006,01/01/2026,CEASA SP,101,55,163.39,MATEUS,1006,163.39,2026-01-01,1,2026
1,NF-1046,01/01/2026,CEASA SP,102,119,335.78,THIAGO,1046,335.78,2026-01-01,1,2026
2,NF-1018,01/01/2026,CEASA SP,103,115,243.92,THIAGO,1018,243.92,2026-01-01,1,2026
3,NF-1013,01/01/2026,CEASA SP,104,41,123.78,DIEGO,1013,123.78,2026-01-01,1,2026
4,NF-1004,01/01/2026,CEASA SP,105,85,235.48,DIEGO,1004,235.48,2026-01-01,1,2026

------

In [16]:
resultado = True

In [17]:
silverCompras['COD_PROD'].isna().value_counts() # Confere quantidade de null

COD_PROD
False    402
Name: count, dtype: int64

In [18]:
silverCompras['COD_PROD'] = silverCompras['COD_PROD'].fillna(1000001) # trata valores nulos

In [19]:
silverCompras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO,N_NF,TOTAL_NOTA,DATA,MES,ANO
0,NF-1006,01/01/2026,CEASA SP,101,55,163.39,MATEUS,1006,163.39,2026-01-01,1,2026
1,NF-1046,01/01/2026,CEASA SP,102,119,335.78,THIAGO,1046,335.78,2026-01-01,1,2026
2,NF-1018,01/01/2026,CEASA SP,103,115,243.92,THIAGO,1018,243.92,2026-01-01,1,2026
3,NF-1013,01/01/2026,CEASA SP,104,41,123.78,DIEGO,1013,123.78,2026-01-01,1,2026
4,NF-1004,01/01/2026,CEASA SP,105,85,235.48,DIEGO,1004,235.48,2026-01-01,1,2026

In [20]:
silverCompras['FORNECEDOR'].value_counts()

FORNECEDOR
CEASA SP              242
FRIGORIFICO FRIBOI    160
Name: count, dtype: int64

In [21]:
MAPA_FORNECEDOR = {
    'CEASA SP': 1001,
    'FRIGORIFICO FRIBOI': 1002,
}

silverCompras['ID_FORNECEDOR'] = (
    silverCompras['FORNECEDOR']
    .str.strip()
    .str.upper()
    .map(MAPA_FORNECEDOR)
    .fillna(0)
    .astype('Int64')
)

silverCompras['ID_FORNECEDOR'].head(5)

0    1001
1    1001
2    1001
3    1001
4    1001
Name: ID_FORNECEDOR, dtype: Int64

In [22]:
silverCompras['QTD_COMPRADA'] = silverCompras['QTD_COMPRADA'].astype(float)

silverCompras['PRECO_UNIT'] = pd.to_numeric(silverCompras['TOTAL_NOTA']) / silverCompras['QTD_COMPRADA']
silverCompras['PRECO_UNIT'].head(5)

0    2.970727
1    2.821681
2    2.121043
3    3.019024
4    2.770353
Name: PRECO_UNIT, dtype: float64

In [23]:
# silverCompras['DIA'] = silverCompras['DATA_ENTRADA'].split('/%d/%YYYY')
# silverCompras['DIA'].head(5)

silverCompras['DATA_ENTRADA'] = pd.to_datetime(
    silverCompras['DATA_ENTRADA'],
    format='%d/%m/%Y',
    errors='coerce'
)

silverCompras['DIA'] = silverCompras['DATA_ENTRADA'].dt.day.astype('Int64')
silverCompras['DIA'].head(5)

0    1
1    1
2    1
3    1
4    1
Name: DIA, dtype: Int64

In [24]:
silverCompras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO,N_NF,TOTAL_NOTA,DATA,MES,ANO,ID_FORNECEDOR,PRECO_UNIT,DIA
0,NF-1006,2026-01-01,CEASA SP,101,55.0,163.39,MATEUS,1006,163.39,2026-01-01,1,2026,1001,2.970727,1
1,NF-1046,2026-01-01,CEASA SP,102,119.0,335.78,THIAGO,1046,335.78,2026-01-01,1,2026,1001,2.821681,1
2,NF-1018,2026-01-01,CEASA SP,103,115.0,243.92,THIAGO,1018,243.92,2026-01-01,1,2026,1001,2.121043,1
3,NF-1013,2026-01-01,CEASA SP,104,41.0,123.78,DIEGO,1013,123.78,2026-01-01,1,2026,1001,3.019024,1
4,NF-1004,2026-01-01,CEASA SP,105,85.0,235.48,DIEGO,1004,235.48,2026-01-01,1,2026,1001,2.770353,1

In [25]:
def export_dados_excel(resultado):

    pasta = Path(r"C:\Users\Public\Teste_Jupyter\Mercado\2 - Silver")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "silverCompras_ETL.xlsx"

        # 1. Criar os arquivos
        silverCompras.to_excel(arquivo_excel, index=False)

        # 3. Consolidar em um Excel com duas abas
        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            silverCompras.to_excel(
                writer,
                sheet_name="Excel",
                index=False
            )

        return True

    print("ERRO")
    return False

In [26]:
export_dados_excel(resultado)

True