In [492]:
%run "../0 - Base/inicializa.ipynb"

In [493]:
DF_Compras = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\NewStudy_04-10\\RAW_COMPRAS_ENTRADAS.csv")

In [494]:
DF_Compras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO
0,NF-1006,01/01/2026,CEASA SP - PRODUTORES UNIDOS,101,55,163.39,Mateus
1,NF-1046,01/01/2026,CEASA SP - PRODUTORES UNIDOS,102,119,335.78,Thiago
2,NF-1018,01/01/2026,CEASA SP - PRODUTORES UNIDOS,103,115 KG,243.92,Thiago
3,NF-1013,01/01/2026,CEASA SP - PRODUTORES UNIDOS,104,41,123.78,diego
4,NF-1004,01/01/2026,CEASA SP - PRODUTORES UNIDOS,105,85,235.48,Diego

-----

In [495]:
DF_Compras['N_NF'] = DF_Compras['NUM_NOTA_FISCAL'].str.replace('NF-','')

In [496]:
DF_Compras['FORNECEDOR'].value_counts()

FORNECEDOR
CEASA SP - PRODUTORES UNIDOS     242
FRIGORIFICO FRIBOI / BOI LEVE    160
Name: count, dtype: int64

In [497]:
DF_Compras['FORNECEDOR'] = DF_Compras['FORNECEDOR'].str.replace(' - PRODUTORES UNIDOS','')

In [498]:
DF_Compras['FORNECEDOR'] = DF_Compras['FORNECEDOR'].str.replace(' / BOI LEVE','')

In [499]:
DF_Compras['QTD_COMPRADA'] = DF_Compras['QTD_COMPRADA'].str.replace('KG','')

In [500]:
DF_Compras['TOTAL_NOTA'] = DF_Compras['VALOR_TOTAL_NOTA'].str.replace(',','.')

In [501]:
pd.to_numeric(DF_Compras['TOTAL_NOTA'], errors="coerce")

0       163.39
1       335.78
2       243.92
3       123.78
4       235.48
        ...
397     239.64
398     566.55
399     197.98
400     240.59
401    1536.61
Name: TOTAL_NOTA, Length: 402, dtype: float64

-----

In [502]:
DF_Compras['RESPONSAVEL_RECEBIMENTO'] = DF_Compras['RESPONSAVEL_RECEBIMENTO'].str.upper()

In [503]:
DF_Compras['DATA'] = pd.to_datetime(DF_Compras['DATA_ENTRADA'], format='%d/%m/%Y')

DF_Compras['MES'] = DF_Compras['DATA'].dt.month
DF_Compras['ANO'] = DF_Compras['DATA'].dt.year

In [504]:

DF_Compras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO,N_NF,TOTAL_NOTA,DATA,MES,ANO
0,NF-1006,01/01/2026,CEASA SP,101,55,163.39,MATEUS,1006,163.39,2026-01-01,1,2026
1,NF-1046,01/01/2026,CEASA SP,102,119,335.78,THIAGO,1046,335.78,2026-01-01,1,2026
2,NF-1018,01/01/2026,CEASA SP,103,115,243.92,THIAGO,1018,243.92,2026-01-01,1,2026
3,NF-1013,01/01/2026,CEASA SP,104,41,123.78,DIEGO,1013,123.78,2026-01-01,1,2026
4,NF-1004,01/01/2026,CEASA SP,105,85,235.48,DIEGO,1004,235.48,2026-01-01,1,2026

------

In [505]:
# def exportar_dados_excel(resultado):

#     pasta = Path(r"C:\Users\Public\Teste_Jupyter\Mercado\2 - Silver")
#     pasta.mkdir(parents=True, exist_ok=True)

#     if resultado:

#         arquivo_excel = pasta / "silverPerdas_ETL.xlsx"
#         arquivo_csv = pasta / "silverPerdas_ETL.csv"

#         df_csv = pd.read_csv(arquivo_csv)

#         with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

#             SilverCadastro_ETL.to_excel(
#                 writer,
#                 sheet_name="xlsx",
#                 index=False
#             )

#             df_csv.to_excel(
#                 writer,
#                 sheet_name="csv",
#                 index=False
#             )

#         return True

#     print("ERRO")
#     return False

In [506]:
resultado = True

In [507]:
silverCompras = DF_Compras

In [508]:
silverCompras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO,N_NF,TOTAL_NOTA,DATA,MES,ANO
0,NF-1006,01/01/2026,CEASA SP,101,55,163.39,MATEUS,1006,163.39,2026-01-01,1,2026
1,NF-1046,01/01/2026,CEASA SP,102,119,335.78,THIAGO,1046,335.78,2026-01-01,1,2026
2,NF-1018,01/01/2026,CEASA SP,103,115,243.92,THIAGO,1018,243.92,2026-01-01,1,2026
3,NF-1013,01/01/2026,CEASA SP,104,41,123.78,DIEGO,1013,123.78,2026-01-01,1,2026
4,NF-1004,01/01/2026,CEASA SP,105,85,235.48,DIEGO,1004,235.48,2026-01-01,1,2026

In [509]:
def export_dados_excel(resultado):

    pasta = Path(r"C:\Users\Public\Teste_Jupyter\Mercado\2 - Silver")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "silverCompras_ETL.xlsx"
        arquivo_csv = pasta / "silverCompras_ETL.csv"

        # 1. Criar os arquivos
        silverCompras.to_csv(arquivo_csv, index=False)
        silverCompras.to_excel(arquivo_excel, index=False)

        # 2. Ler o CSV criado
        df_csv = pd.read_csv(arquivo_csv)

        # 3. Consolidar em um Excel com duas abas
        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            silverCompras.to_excel(
                writer,
                sheet_name="Excel",
                index=False
            )

            df_csv.to_excel(
                writer,
                sheet_name="CSV",
                index=False
            )

        return True

    print("ERRO")
    return False

In [510]:
export_dados_excel(resultado)

True