In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
%run "../1 - Bronze/Consulta_Tabelas.ipynb"

In [3]:
DF_Cadastro.head(5)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,Tomate Debora kg,"7,90",3.2
1,102,Horti Fruti,BANANA PRATA KG,5.5,"2,10"
2,103,Hortifruti,Alface Americana un,3.5,1.2
3,104,HORTI,Batata Monalisa kg,5.9,2.5
4,105,Hortifruti,Cebola Nacional kg,NaN,2.8

## AJUSTAR COLUNAS

-----------

In [4]:
DF_Cadastro_Novo = DF_Cadastro

DF_Cadastro_Novo['CATEGORIA_BRUTA'] = DF_Cadastro_Novo['CATEGORIA_BRUTA'].str.upper()

In [5]:
DF_Cadastro_Novo['NOME_PRODUTO'] = DF_Cadastro_Novo['NOME_PRODUTO'].str.upper()

In [6]:
silverCadastro = DF_Cadastro_Novo

In [7]:
silverCadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,TOMATE DEBORA KG,"7,90",3.2
1,102,HORTI FRUTI,BANANA PRATA KG,5.5,"2,10"
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2
3,104,HORTI,BATATA MONALISA KG,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,NaN,2.8
5,201,CARNES,PICANHA BOV RESFRIADA KG,79.9,42.0
6,202,CARNES,ALCATRA C/ MAMINHA KG,44.9,26.0
7,203,CARNES & AÇOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0
8,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0
9,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0

----

### Lembre usar .str.upper() não .upper()
### DF_Cadastro['NOME_COLUNA'] precisa aponta -  se nao criar nova tabela apenas com coluan

--------

In [8]:
# REGRAS_PRODUTO = {
#     "  ":" ",
#     " ":"_",
#     "_PCA": "",
#     "_LATA": "",
#     "_CX": "",
#     "_KG": "",
#     "_kg": "",
#     "_UN": "",
#     "_un": "",
#     "_1L": "",
#     "_2L": "",
#     "_5L": "",
#     "_5KG": "",
#     "_1KG": "",
#     "_200G": "",
#     "_900ML": "",
#     "_350ML": "",
#     "_500G": "",
#     "_DE_": "",
# }

# silverCadastro["NOME_PRODUTO"] = (
#     silverCadastro["NOME_PRODUTO"]
#     .astype(str)
#     .str.replace(REGRAS_PRODUTO, regex=False)
# )

In [9]:
silverCadastro.head(5)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,TOMATE DEBORA KG,"7,90",3.2
1,102,HORTI FRUTI,BANANA PRATA KG,5.5,"2,10"
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2
3,104,HORTI,BATATA MONALISA KG,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,NaN,2.8

# Criando regra ETL

----------------

In [10]:
REGRAS_CATEGORIA = {
    "FRIOS & LATICINIOS": "FRIOS E LATICINIOS",
    "FRIOS": "FRIOS E LATICINIOS",
    "LATICINIOS": "FRIOS E LATICINIOS",
    "SECOS E MOLHADOS": "SECOS E MOLHADOS",
    "SECOS": "SECOS E MOLHADOS",
    "MOLHADOS": "SECOS E MOLHADOS",
    "HORTI FRUTI": "HORTIFRUTI",
    "HORT": "HORTIFRUTI",
    "HORTI": "HORTIFRUTI",

}

silverCadastro["CATEGORIA_BRUTA"] = (
    silverCadastro["CATEGORIA_BRUTA"]
    .replace(REGRAS_CATEGORIA)
)

In [11]:
silverCadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,TOMATE DEBORA KG,"7,90",3.2
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,"2,10"
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,NaN,2.8
5,201,CARNES,PICANHA BOV RESFRIADA KG,79.9,42.0
6,202,CARNES,ALCATRA C/ MAMINHA KG,44.9,26.0
7,203,CARNES & AÇOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0
8,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0
9,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0

----

In [12]:
vt_VendasCadastro = silverCadastro['VALOR_VENDA_CADASTRO']
vs_VendasCadastro = "vt_VendasCadastro"

In [13]:
vt_CustoCadastro = silverCadastro['CUSTO_CADASTRO']
vs_CustoCadastro = "vt_CustoCadastro"

In [14]:
print(vt_CustoCadastro)

0      3.2
1     2,10
2      1.2
3      2.5
4      2.8
5     42.0
6     26.0
7     14.0
8     12.0
9     12.0
10    26.0
11    15.0
12     3.4
13     4.2
14    18.5
15     4.1
16     4.5
17    11.5
18     2.2
19     4.8
20     3.1
21     4.0
22     5.5
Name: CUSTO_CADASTRO, dtype: str

-----

In [15]:
def clean_numeric_column(series: pd.Series) -> pd.Series:
    return pd.to_numeric(
        series.astype(str)
              .str.strip()
              .str.replace(',', '.', regex=False),
        errors='coerce'
    ).fillna(0.0)


silverCadastro['VENDA_CADASTRO'] = clean_numeric_column(vt_VendasCadastro)

silverCadastro['CUSTO_VENDA'] = clean_numeric_column(vt_CustoCadastro)

In [16]:
vt_VendasCadastro = silverCadastro['VENDA_CADASTRO']
vs_VendasCadastro = "silverCadastro['VENDA_CADASTRO']"
vt_CustoCadastro = silverCadastro['CUSTO_VENDA']
vs_CustoCadastro = "silverCadastro['CUSTO_VENDA']"

In [17]:
silverCadastro.head(6)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO,VENDA_CADASTRO,CUSTO_VENDA
0,101,HORTIFRUTI,TOMATE DEBORA KG,"7,90",3.2,7.9,3.2
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,"2,10",5.5,2.1
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2,3.5,1.2
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,NaN,2.8,0.0,2.8
5,201,CARNES,PICANHA BOV RESFRIADA KG,79.9,42.0,79.9,42.0

In [18]:
silverCadastro = silverCadastro.drop(columns=['VALOR_VENDA_CADASTRO','CUSTO_CADASTRO'])

In [19]:
silverCadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA
0,101,HORTIFRUTI,TOMATE DEBORA KG,7.9,3.2
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,2.1
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,0.0,2.8
5,201,CARNES,PICANHA BOV RESFRIADA KG,79.9,42.0
6,202,CARNES,ALCATRA C/ MAMINHA KG,44.9,26.0
7,203,CARNES & AÇOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0
8,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0
9,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0

In [20]:
silverCadastro['MARGEM'] = vt_VendasCadastro - vt_CustoCadastro

In [21]:
silverCadastro.head()

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA,MARGEM
0,101,HORTIFRUTI,TOMATE DEBORA KG,7.9,3.2,4.7
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,2.1,3.4
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2,2.3
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5,3.4
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,0.0,2.8,-2.8

### CRIANDO NOVA TABELA COM MEDIDAS

In [22]:
silverCadastro['PROD'] = DF_Cadastro['NOME_PRODUTO']
silverCadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA,MARGEM,PROD
0,101,HORTIFRUTI,TOMATE DEBORA KG,7.9,3.2,4.7,TOMATE DEBORA KG
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,2.1,3.4,BANANA PRATA KG
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2,2.3,ALFACE AMERICANA UN
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5,3.4,BATATA MONALISA KG
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,0.0,2.8,-2.8,CEBOLA NACIONAL KG
5,201,CARNES,PICANHA BOV RESFRIADA KG,79.9,42.0,37.9,PICANHA BOV RESFRIADA KG
6,202,CARNES,ALCATRA C/ MAMINHA KG,44.9,26.0,18.9,ALCATRA C/ MAMINHA KG
7,203,CARNES & AÇOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0,15.9,CARNE MOIDA DE 2A KG
8,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0,10.9,LINGUICA TOSCANA KG
9,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0,10.9,LINGUICA TOSCANA KG

# Criando outra forma usar regra ETL

-------------

In [23]:
padrao = r'(\d+(?:[.,]\d+)?)?\s*(KG|G|MG|L|LT|ML|CM|CX|M|UN|PCA)\b'
       

silverCadastro[["MEDIDA", "UNIDADE"]] = (
    silverCadastro["PROD"]
    .str.extract(padrao, flags=re.IGNORECASE)
)

In [24]:
silverCadastro["PROD"] = (
    silverCadastro["PROD"]
    .str.replace(padrao, '', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [25]:
silverCadastro.head(5)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA,MARGEM,PROD,MEDIDA,UNIDADE
0,101,HORTIFRUTI,TOMATE DEBORA KG,7.9,3.2,4.7,TOMATE DEBORA,NaN,KG
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,2.1,3.4,BANANA PRATA,NaN,KG
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2,2.3,ALFACE AMERICANA,NaN,UN
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5,3.4,BATATA MONALISA,NaN,KG
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,0.0,2.8,-2.8,CEBOLA NACIONA,NaN,L

In [26]:
vt_medid = silverCadastro["MEDIDA"]
vs_medid = 'silverCadastro["MEDIDA"]'

#### vt_Medida recebe tabela x vs_Medida recebe string com caminho da tabela

In [27]:
#vt_medid = pd.to_numeric(vt_medid.replace(np.nan, 1))

In [28]:
silverCadastro["MEDIDA"] = pd.to_numeric(silverCadastro["MEDIDA"].replace(np.nan, 1))

In [29]:
silverCadastro["MEDIDA"].head(5)

0    1
1    1
2    1
3    1
4    1
Name: MEDIDA, dtype: int64

-----

## Finalizado

In [30]:
SilverCadastro_ETL = silverCadastro

In [31]:
def exportar_dados_csv(resultado):

    pasta = Path(r"C:\Users\Public\Teste_Jupyter\Mercado\2 - Silver")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:
        SilverCadastro_ETL.to_csv(
            pasta / "SilverCadastro_ETL.csv",
            index=False
        )
        return True

    print("ERRO")
    return False

In [32]:
resultado = True

In [33]:
exportar_dados_csv(resultado)

True

In [34]:
def exportar_dados_excel(resultado):

    pasta = Path(r"C:\Users\Public\Teste_Jupyter\Mercado\2 - Silver")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "SilverCadastro_ETL.xlsx"
        arquivo_csv = pasta / "SilverCadastro_ETL.csv"

        df_csv = pd.read_csv(arquivo_csv)

        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            SilverCadastro_ETL.to_excel(
                writer,
                sheet_name="xlsx",
                index=False
            )

            df_csv.to_excel(
                writer,
                sheet_name="csv",
                index=False
            )

        return True

    print("ERRO")
    return False

In [35]:
exportar_dados_excel(resultado)

True