In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
DF_Perdas = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\NewStudy_04-10\\RAW_CADERNO_PERDAS.csv")

In [3]:
DF_Perdas.head(10)

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO_MOTIVO_TEXTO_LIVRE,COD_PROD_OU_NOME,QTD_AVARIADA,VALOR_ESTIMADO_PREJUIZO,REGISTRADO_POR
0,01/01/2026,DEPOSITO,Falta de mercadoria no estoque - suspeita furto,601,1.10,"R$ 14,18",Diego
1,03/01/2026,HORTI,podre descartado no lixo,601,6.92,"R$ 100,71",Betao
2,04/01/2026,Açougue,Lata amassada no descarregamento,DIFERENCA CAIXA,7.95,"R$ 98,53",Betao
3,06/01/2026,CARNES,Diferenca de peso na balanca,501,1.07,"R$ 19,3",DESCONHECIDO
4,07/01/2026,HORTI,Sobra de pao dormido,PAO,4.59,"R$ 158,44",Diego
5,10/01/2026,Açougue,quebra de caixa operadora Juliana,101,1.13,"R$ 136,15",Juliana
6,12/01/2026,Padaria,Diferenca de peso na balanca,501,11.24,"R$ 64,3",Carlos
7,14/01/2026,hortifruti,podre descartado no lixo,201,12.60,"R$ 155,74",Diego
8,17/01/2026,Açougue,produto vencido na prateleira sem etiqueta,601,11.76,"R$ 67,76",Carlos
9,18/01/2026,frente de caixa,Falta de mercadoria no estoque - suspeita furto,101,8.83,"R$ 138,33",Carlos

-----

# ETL

In [4]:
silverPerdas = DF_Perdas

In [5]:
sp_Origem_t = silverPerdas['SETOR_ORIGEM']
sp_Registro_t = silverPerdas['REGISTRADO_POR']

In [6]:
sp_Origem_t.str.upper().head(3)

0    DEPOSITO
1       HORTI
2     AÇOUGUE
Name: SETOR_ORIGEM, dtype: str

In [7]:
sp_Origem_t.str.upper().head(3)

0    DEPOSITO
1       HORTI
2     AÇOUGUE
Name: SETOR_ORIGEM, dtype: str

----

## ETL com loop

In [8]:
silverPerdas = silverPerdas.rename(columns={
    'COD_PROD_OU_NOME':'COD_PROD',
    'REGISTRADO_POR':'RESPONSAVEL',
    'VALOR_ESTIMADO_PREJUIZO':'PREJUIZO_ESTIMADO',
    'DESCRICAO_MOTIVO_TEXTO_LIVRE':'DESCRICAO'
})

In [9]:
# Lista com o nome das colunas
colunas = ['SETOR_ORIGEM', 'RESPONSAVEL', 'DESCRICAO']

# Aplica .str.upper() em cada coluna individualmente
for col in colunas:
    silverPerdas[col] = silverPerdas[col].astype(str).str.upper()

# Exibe o resultado
silverPerdas[colunas].head(3)

  SETOR_ORIGEM RESPONSAVEL                                        DESCRICAO
0     DEPOSITO       DIEGO  FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO
1        HORTI       BETAO                         PODRE DESCARTADO NO LIXO
2      AÇOUGUE       BETAO                 LATA AMASSADA NO DESCARREGAMENTO

In [10]:
silverPerdas.head(5)

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO,COD_PROD,QTD_AVARIADA,PREJUIZO_ESTIMADO,RESPONSAVEL
0,01/01/2026,DEPOSITO,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,601,1.10,"R$ 14,18",DIEGO
1,03/01/2026,HORTI,PODRE DESCARTADO NO LIXO,601,6.92,"R$ 100,71",BETAO
2,04/01/2026,AÇOUGUE,LATA AMASSADA NO DESCARREGAMENTO,DIFERENCA CAIXA,7.95,"R$ 98,53",BETAO
3,06/01/2026,CARNES,DIFERENCA DE PESO NA BALANCA,501,1.07,"R$ 19,3",DESCONHECIDO
4,07/01/2026,HORTI,SOBRA DE PAO DORMIDO,PAO,4.59,"R$ 158,44",DIEGO

---

In [11]:
sp_Origem_t.head()

0    DEPOSITO
1       HORTI
2     Açougue
3      CARNES
4       HORTI
Name: SETOR_ORIGEM, dtype: str

In [12]:
sp_Origem_t = (
    sp_Origem_t
    .str.replace('Ç', 'C', regex=True)
)

In [13]:
silverPerdas.head(5)

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO,COD_PROD,QTD_AVARIADA,PREJUIZO_ESTIMADO,RESPONSAVEL
0,01/01/2026,DEPOSITO,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,601,1.10,"R$ 14,18",DIEGO
1,03/01/2026,HORTI,PODRE DESCARTADO NO LIXO,601,6.92,"R$ 100,71",BETAO
2,04/01/2026,AÇOUGUE,LATA AMASSADA NO DESCARREGAMENTO,DIFERENCA CAIXA,7.95,"R$ 98,53",BETAO
3,06/01/2026,CARNES,DIFERENCA DE PESO NA BALANCA,501,1.07,"R$ 19,3",DESCONHECIDO
4,07/01/2026,HORTI,SOBRA DE PAO DORMIDO,PAO,4.59,"R$ 158,44",DIEGO

In [14]:
sp_Origem_t.value_counts()

SETOR_ORIGEM
DEPOSITO           10
Açougue             7
hortifruti          7
HORTI               6
CARNES              6
Padaria             5
frente de caixa     5
Name: count, dtype: int64

In [15]:
sp_Origem_t = (
    sp_Origem_t
    .str.replace('Ç', 'C', regex=True)
    .str.replace('HORTI', 'HORTIFRUTI')
    .str.replace('CARNES', 'ACOUGUE')
    .str.replace('frente de caixa', 'CAIXA')
)

In [16]:
sp_Origem_t.value_counts()

SETOR_ORIGEM
DEPOSITO      10
Açougue        7
hortifruti     7
HORTIFRUTI     6
ACOUGUE        6
Padaria        5
CAIXA          5
Name: count, dtype: int64

-----

In [17]:
st_CodProd_t = silverPerdas['COD_PROD']
st_CodProd_s = "silverPerdas['COD_PROD']"

In [18]:
st_CodProd_t.value_counts()

COD_PROD
DIFERENCA CAIXA    7
PAO                7
101                6
601                4
501                4
102                3
301                3
PICANHA            3
201                2
Name: count, dtype: int64

### chama cadatro

In [19]:
DF_Cadastro = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\NewStudy_04-10\\RAW_CADASTRO_PRODUTOS.csv")

In [20]:
DF_Cadastro.head(25)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,Tomate Debora kg,"7,90",3.2
1,102,Horti Fruti,BANANA PRATA KG,5.5,"2,10"
2,103,Hortifruti,Alface Americana un,3.5,1.2
3,104,HORTI,Batata Monalisa kg,5.9,2.5
4,105,Hortifruti,Cebola Nacional kg,NaN,2.8
5,201,Carnes,Picanha Bov Resfriada kg,79.9,42.0
6,202,CARNES,Alcatra c/ Maminha kg,44.9,26.0
7,203,Carnes & Açougue,Carne Moida de 2a kg,29.9,14.0
8,204,Carnes,Linguica Toscana kg,22.9,12.0
9,204,Carnes,Linguica Toscana kg,22.9,12.0
10,301,Frios & Laticinios,Queijo Mussarela Pca kg,42.9,26.0
11,302,FRIOS,Presunto Cozido kg,28.9,15.0
12,303,Laticinios,Leite Integral 1L cx,5.29,3.4
13,304,Frios,Requeijao Cremos 200g,0.0,4.2
14,401,Secos e Molhados,Arroz Tipo 1 5kg,25.9,18.5
15,402,SECOS,Feijao Carioca 1kg,6.99,4.1
16,403,Secos e Molhados,Oleo de Soja 900ml,6.49,4.5
17,404,Mercearia,Cafe Torrado 500g,16.9,11.5
18,501,BEBIDAS,Cerveja Pilsen Lata 350ml,3.89,2.2
19,502,Bebidas,Refrigerante Cola 2L,8.49,4.8
20,503,Bebidas,Suco Caixinha 1L,5.90,3.1
21,601,Padaria,Pao Frances kg,13.9,4.0
22,602,PADARIA,Bolo Caseiro un,14.9,5.5

In [21]:
# Busca qualquer produto na DF_Cadastro que contenha "PAO" (ignorando maiúsculas/minúsculas)
df_pao = DF_Cadastro.loc[DF_Cadastro['NOME_PRODUTO'].astype(str).str.contains('PAO', case=False, na=False)]
df_pao

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
21,601,Padaria,Pao Frances kg,13.9,4.0

In [22]:
df_picanha = DF_Cadastro.loc[DF_Cadastro['NOME_PRODUTO'].astype(str).str.contains('PICANHA', case=False, na=False)]
df_picanha

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
5,201,Carnes,Picanha Bov Resfriada kg,79.9,42.0

In [23]:
silverPerdas['COD_PROD'] = (
    st_CodProd_t
    .str.strip()
    .str.replace('DIFERENCA CAIXA', '1000001')
    .str.replace('PICANHA', '201')
    .str.replace('PAO', '601')
)

In [24]:
silverPerdas.head(5)

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO,COD_PROD,QTD_AVARIADA,PREJUIZO_ESTIMADO,RESPONSAVEL
0,01/01/2026,DEPOSITO,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,601,1.10,"R$ 14,18",DIEGO
1,03/01/2026,HORTI,PODRE DESCARTADO NO LIXO,601,6.92,"R$ 100,71",BETAO
2,04/01/2026,AÇOUGUE,LATA AMASSADA NO DESCARREGAMENTO,1000001,7.95,"R$ 98,53",BETAO
3,06/01/2026,CARNES,DIFERENCA DE PESO NA BALANCA,501,1.07,"R$ 19,3",DESCONHECIDO
4,07/01/2026,HORTI,SOBRA DE PAO DORMIDO,601,4.59,"R$ 158,44",DIEGO

-------

### AJUSTA DATA

#### Cria data com datetime

In [25]:
sp_Data = silverPerdas['DATA_OCORRENCIA']

In [26]:
# 1. Converte a coluna original de data
silverPerdas['DATA'] = pd.to_datetime(silverPerdas['DATA_OCORRENCIA'], format='%d/%m/%Y')

# 2. Extrai apenas o ano como número inteiro (2026)
silverPerdas['ANO'] = silverPerdas['DATA'].dt.year
silverPerdas['MES'] = silverPerdas['DATA'].dt.month
silverPerdas.head(5)

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO,COD_PROD,QTD_AVARIADA,PREJUIZO_ESTIMADO,RESPONSAVEL,DATA,ANO,MES
0,01/01/2026,DEPOSITO,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,601,1.10,"R$ 14,18",DIEGO,2026-01-01,2026,1
1,03/01/2026,HORTI,PODRE DESCARTADO NO LIXO,601,6.92,"R$ 100,71",BETAO,2026-01-03,2026,1
2,04/01/2026,AÇOUGUE,LATA AMASSADA NO DESCARREGAMENTO,1000001,7.95,"R$ 98,53",BETAO,2026-01-04,2026,1
3,06/01/2026,CARNES,DIFERENCA DE PESO NA BALANCA,501,1.07,"R$ 19,3",DESCONHECIDO,2026-01-06,2026,1
4,07/01/2026,HORTI,SOBRA DE PAO DORMIDO,601,4.59,"R$ 158,44",DIEGO,2026-01-07,2026,1

In [27]:
silverPerdas.drop('DATA_OCORRENCIA', axis=1).head(5)

,SETOR_ORIGEM,DESCRICAO,COD_PROD,QTD_AVARIADA,PREJUIZO_ESTIMADO,RESPONSAVEL,DATA,ANO,MES
0,DEPOSITO,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,601,1.10,"R$ 14,18",DIEGO,2026-01-01,2026,1
1,HORTI,PODRE DESCARTADO NO LIXO,601,6.92,"R$ 100,71",BETAO,2026-01-03,2026,1
2,AÇOUGUE,LATA AMASSADA NO DESCARREGAMENTO,1000001,7.95,"R$ 98,53",BETAO,2026-01-04,2026,1
3,CARNES,DIFERENCA DE PESO NA BALANCA,501,1.07,"R$ 19,3",DESCONHECIDO,2026-01-06,2026,1
4,HORTI,SOBRA DE PAO DORMIDO,601,4.59,"R$ 158,44",DIEGO,2026-01-07,2026,1

In [28]:

silverPerdas['DATA'].info()

<class 'pandas.Series'>
RangeIndex: 46 entries, 0 to 45
Series name: DATA
Non-Null Count  Dtype
--------------  -----
46 non-null     datetime64[us]
dtypes: datetime64[us](1)
memory usage: 500.0 bytes

----

### VALORES AJUSTE

In [29]:
sp_Prejuizo = silverPerdas['PREJUIZO_ESTIMADO']

In [30]:
silverPerdas['V_PREJUIZO'] = sp_Prejuizo.str.replace("R$ ","")
sp_Prejuizo = silverPerdas['V_PREJUIZO'].str.replace(",",".")
silverPerdas['V_PREJUIZO'] = pd.to_numeric(sp_Prejuizo)

In [31]:
sp_Data.info()

<class 'pandas.Series'>
RangeIndex: 46 entries, 0 to 45
Series name: DATA_OCORRENCIA
Non-Null Count  Dtype
--------------  -----
46 non-null     str
dtypes: str(1)
memory usage: 500.0 bytes

In [32]:
silverPerdas.head(5)

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO,COD_PROD,QTD_AVARIADA,PREJUIZO_ESTIMADO,RESPONSAVEL,DATA,ANO,MES,V_PREJUIZO
0,01/01/2026,DEPOSITO,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,601,1.10,"R$ 14,18",DIEGO,2026-01-01,2026,1,14.18
1,03/01/2026,HORTI,PODRE DESCARTADO NO LIXO,601,6.92,"R$ 100,71",BETAO,2026-01-03,2026,1,100.71
2,04/01/2026,AÇOUGUE,LATA AMASSADA NO DESCARREGAMENTO,1000001,7.95,"R$ 98,53",BETAO,2026-01-04,2026,1,98.53
3,06/01/2026,CARNES,DIFERENCA DE PESO NA BALANCA,501,1.07,"R$ 19,3",DESCONHECIDO,2026-01-06,2026,1,19.30
4,07/01/2026,HORTI,SOBRA DE PAO DORMIDO,601,4.59,"R$ 158,44",DIEGO,2026-01-07,2026,1,158.44

-------

In [67]:
resultado = True

In [71]:
def export_dados_excel(resultado):

    pasta = Path(r"C:\Users\Public\Teste_Jupyter\Mercado\2 - Silver")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "silverPerdas_ETL.xlsx"
        arquivo_csv = pasta / "silverPerdas_ETL.csv"

        # 1. Criar os arquivos
        silverPerdas.to_csv(arquivo_csv, index=False)
        silverPerdas.to_excel(arquivo_excel, index=False)

        # 2. Ler o CSV criado
        df_csv = pd.read_csv(arquivo_csv)

        # 3. Consolidar em um Excel com duas abas
        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            silverPerdas.to_excel(
                writer,
                sheet_name="Excel",
                index=False
            )

            df_csv.to_excel(
                writer,
                sheet_name="CSV",
                index=False
            )

        return True

    print("ERRO")
    return False

In [72]:
export_dados_excel(resultado)

True