In [10]:
%run "../0 - Base/inicializa.ipynb"

In [11]:
DF_Vendas = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\NewStudy_04-10\\RAW_VENDAS_POS.csv")

In [12]:
DF_Vendas.head(5)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA
0,900001,2026-01-01,CAIXA_PRINCIPAL,Juliana,503.0,5.0,3.94,19.70,FIADO_CADERNETO,CONCLUIDA
1,900002,2026-01-01,caixa 02,Patricia,NaN,2.0,34.47,68.94,FIADO_CADERNETO,CONCLUIDA
2,900003,2026-01-01,caixa 02,Patricia,404.0,4.0,32.32,129.28,FIADO_CADERNETO,CONCLUIDA
3,900004,2026-01-01,caixa 02,Patricia,303.0,4.0,36.05,144.20,CARTAO_CREDITO,CONCLUIDA
4,900005,2026-01-01,CX_02,Patricia,304.0,5.0,25.25,126.25,Cartao Debito,CONCLUIDA

----------

# ETL

### Padroniza Caixa

In [13]:
DF_Vendas['PDV_CAIXA'].value_counts()

PDV_CAIXA
caixa 02           3226
CAIXA_PRINCIPAL    3169
CAIXA 1            3152
CX_02              3145
CX_01              3130
Name: count, dtype: int64

In [14]:
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('caixa 02','CAIXA_02')
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('CAIXA_PRINCIPAL','CAIXA_P')
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('CAIXA 1','CAIXA_01')
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('CX_02','CAIXA_02')
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('CX_01','CAIXA_01')

In [15]:
DF_Vendas['PDV_CAIXA'].value_counts()

PDV_CAIXA
CAIXA_02    6371
CAIXA_01    6282
CAIXA_P     3169
Name: count, dtype: int64

In [16]:
DF_Vendas.head(3)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA
0,900001,2026-01-01,CAIXA_P,Juliana,503.0,5.0,3.94,19.70,FIADO_CADERNETO,CONCLUIDA
1,900002,2026-01-01,CAIXA_02,Patricia,NaN,2.0,34.47,68.94,FIADO_CADERNETO,CONCLUIDA
2,900003,2026-01-01,CAIXA_02,Patricia,404.0,4.0,32.32,129.28,FIADO_CADERNETO,CONCLUIDA

-----

### Trata nulos

In [17]:
DF_Vendas['COD_PRODUTO'].fillna(0).value_counts() # Limpa nulos e substitui 0

COD_PRODUTO
0.0      1306
102.0     684
403.0     680
302.0     672
104.0     667
201.0     661
105.0     659
401.0     650
501.0     645
999.0     643
103.0     632
301.0     631
303.0     627
101.0     623
202.0     620
203.0     619
503.0     614
502.0     608
304.0     607
204.0     606
601.0     602
602.0     601
402.0     600
404.0     565
Name: count, dtype: int64

In [18]:
DF_Vendas['QTD_VENDIDA'].value_counts()

QTD_VENDIDA
1.0    3207
5.0    3200
2.0    3172
4.0    3144
3.0    3099
Name: count, dtype: int64

In [19]:
DF_Vendas.head(3)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA
0,900001,2026-01-01,CAIXA_P,Juliana,503.0,5.0,3.94,19.70,FIADO_CADERNETO,CONCLUIDA
1,900002,2026-01-01,CAIXA_02,Patricia,NaN,2.0,34.47,68.94,FIADO_CADERNETO,CONCLUIDA
2,900003,2026-01-01,CAIXA_02,Patricia,404.0,4.0,32.32,129.28,FIADO_CADERNETO,CONCLUIDA

### Padroniza Operador

In [20]:
DF_Vendas['OPERADOR'].value_counts()

OPERADOR
Juliana             8950
Patricia            6012
Carlos (Gerente)     309
SISTEMA              284
Name: count, dtype: int64

In [21]:
DF_Vendas['OPERADOR'] = DF_Vendas['OPERADOR'].str.replace('Carlos (Gerente)','Carlos_Ger')
DF_Vendas['OPERADOR'] = DF_Vendas['OPERADOR'].str.replace('SISTEMA','N_IDENTIFICADO')
DF_Vendas['OPERADOR'] = DF_Vendas['OPERADOR'].str.upper()
DF_Vendas['OPERADOR'].value_counts()

OPERADOR
JULIANA           8950
PATRICIA          6012
CARLOS_GER         309
N_IDENTIFICADO     284
Name: count, dtype: int64

In [24]:
DF_Vendas['STATUS_VENDA'].value_counts()

STATUS_VENDA
CONCLUIDA    9051
ESTORNADA    2298
ABERTO       2247
CANCELADA    2226
Name: count, dtype: int64

In [25]:
DF_Vendas['STATUS_VENDA'] = DF_Vendas['STATUS_VENDA'].str.replace('EM_ABERTO','ABERTO')

In [26]:
DF_Vendas['STATUS_VENDA'].value_counts()

STATUS_VENDA
CONCLUIDA    9051
ESTORNADA    2298
ABERTO       2247
CANCELADA    2226
Name: count, dtype: int64

### Padroniza pagamentos

In [45]:
DF_Vendas['FORMA_PAGTO'].value_counts() #Antes ajuste

FORMA_PAGTO
FIADO_CADERNETO    2062
Cartao Debito      2018
DIVERSOS           1991
Pix                1959
DINHEIRO           1942
PIX                1933
CARTAO_CREDITO     1921
Name: count, dtype: int64

In [46]:
# Realiza modificacoes
DF_Vendas['FORMA_PAGTO'] = DF_Vendas['FORMA_PAGTO'].str.replace('Cartao Debito','CARTAO_DEB')
DF_Vendas['FORMA_PAGTO'] = DF_Vendas['FORMA_PAGTO'].str.replace('DIVERSOS','MISTO')
DF_Vendas['FORMA_PAGTO'] = DF_Vendas['FORMA_PAGTO'].str.replace('Pix','PIX')
DF_Vendas['FORMA_PAGTO'] = DF_Vendas['FORMA_PAGTO'].str.replace('CARTAO_CREDITO','CARTAO_CRED')

In [47]:
DF_Vendas['FORMA_PAGTO'].value_counts() #depois ajuste

FORMA_PAGTO
PIX                3892
FIADO_CADERNETO    2062
CARTAO_DEB         2018
MISTO              1991
DINHEIRO           1942
CARTAO_CRED        1921
Name: count, dtype: int64

## ajusta null

In [48]:
DF_Vendas['COD_PRODUTO'] = DF_Vendas['COD_PRODUTO'].fillna(0)

In [49]:
DF_Vendas.head(5)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA
0,900001,2026-01-01,CAIXA_P,JULIANA,503.0,5.0,3.94,19.70,FIADO_CADERNETO,CONCLUIDA
1,900002,2026-01-01,CAIXA_02,PATRICIA,0.0,2.0,34.47,68.94,FIADO_CADERNETO,CONCLUIDA
2,900003,2026-01-01,CAIXA_02,PATRICIA,404.0,4.0,32.32,129.28,FIADO_CADERNETO,CONCLUIDA
3,900004,2026-01-01,CAIXA_02,PATRICIA,303.0,4.0,36.05,144.20,CARTAO_CRED,CONCLUIDA
4,900005,2026-01-01,CAIXA_02,PATRICIA,304.0,5.0,25.25,126.25,CARTAO_DEB,CONCLUIDA

### Ajusta Data

In [50]:
# Cria coluna Data
DF_Vendas['DATA'] = pd.to_datetime(DF_Vendas['DATA_HORA_VENDA'], format="mixed")

# cria colunas Mes e Ano
DF_Vendas['MES'] = DF_Vendas['DATA'].dt.month
DF_Vendas['ANO'] = DF_Vendas['DATA'].dt.year

# deleta coluna DATA_HORA_VENDA
DF_Vendas = DF_Vendas.drop(columns={'DATA_HORA_VENDA'})

DF_Vendas.head(5)

,ID_TRANSACAO,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA,DATA,MES,ANO
0,900001,CAIXA_P,JULIANA,503.0,5.0,3.94,19.70,FIADO_CADERNETO,CONCLUIDA,2026-01-01,1,2026
1,900002,CAIXA_02,PATRICIA,0.0,2.0,34.47,68.94,FIADO_CADERNETO,CONCLUIDA,2026-01-01,1,2026
2,900003,CAIXA_02,PATRICIA,404.0,4.0,32.32,129.28,FIADO_CADERNETO,CONCLUIDA,2026-01-01,1,2026
3,900004,CAIXA_02,PATRICIA,303.0,4.0,36.05,144.20,CARTAO_CRED,CONCLUIDA,2026-01-01,1,2026
4,900005,CAIXA_02,PATRICIA,304.0,5.0,25.25,126.25,CARTAO_DEB,CONCLUIDA,2026-01-01,1,2026

-----

# SALVAR

In [51]:
resultado = True

In [52]:
silverVendas_ETL = DF_Vendas

In [53]:
def export_dados_excel(resultado):

    pasta = Path(r"C:\Users\Public\Teste_Jupyter\Mercado\2 - Silver")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "silverVendas_ETL.xlsx"
        arquivo_csv = pasta / "silverVendas_ETL.csv"

        # 1. Criar os arquivos
        silverVendas_ETL.to_csv(arquivo_csv, index=False)
        silverVendas_ETL.to_excel(arquivo_excel, index=False)

        # 2. Ler o CSV criado
        df_csv = pd.read_csv(arquivo_csv)

        # 3. Consolidar em um Excel com duas abas
        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            silverVendas_ETL.to_excel(
                writer,
                sheet_name="Excel",
                index=False
            )

            df_csv.to_excel(
                writer,
                sheet_name="CSV",
                index=False
            )

        return True

    print("ERRO")
    return False

In [54]:
export_dados_excel(resultado)

True