In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
%run "../1 - Bronze/Consulta_Tabelas.ipynb"

In [3]:
DF_Cadastro.head(26)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,Tomate Debora kg,"7,90",3.2
1,102,Horti Fruti,BANANA PRATA KG,5.5,"2,10"
2,103,Hortifruti,Alface Americana un,3.5,1.2
3,104,HORTI,Batata Monalisa kg,5.9,2.5
4,105,Hortifruti,Cebola Nacional kg,NaN,2.8
5,201,Carnes,Picanha Bov Resfriada kg,79.9,42.0
6,202,CARNES,Alcatra c/ Maminha kg,44.9,26.0
7,203,Carnes & Açougue,Carne Moida de 2a kg,29.9,14.0
8,204,Carnes,Linguica Toscana kg,22.9,12.0
9,204,Carnes,Linguica Toscana kg,22.9,12.0
10,301,Frios & Laticinios,Queijo Mussarela Pca kg,42.9,26.0
11,302,FRIOS,Presunto Cozido kg,28.9,15.0
12,303,Laticinios,Leite Integral 1L cx,5.29,3.4
13,304,Frios,Requeijao Cremos 200g,0.0,4.2
14,401,Secos e Molhados,Arroz Tipo 1 5kg,25.9,18.5
15,402,SECOS,Feijao Carioca 1kg,6.99,4.1
16,403,Secos e Molhados,Oleo de Soja 900ml,6.49,4.5
17,404,Mercearia,Cafe Torrado 500g,16.9,11.5
18,501,BEBIDAS,Cerveja Pilsen Lata 350ml,3.89,2.2
19,502,Bebidas,Refrigerante Cola 2L,8.49,4.8
20,503,Bebidas,Suco Caixinha 1L,5.90,3.1
21,601,Padaria,Pao Frances kg,13.9,4.0
22,602,PADARIA,Bolo Caseiro un,14.9,5.5

## AJUSTAR COLUNAS

-----------

In [4]:
silverCadastro = DF_Cadastro

silverCadastro['CATEGORIA_BRUTA'] = silverCadastro['CATEGORIA_BRUTA'].str.upper()

In [5]:
silverCadastro['NOME_PRODUTO'] = silverCadastro['NOME_PRODUTO'].str.upper()

In [6]:
silverCadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,TOMATE DEBORA KG,"7,90",3.2
1,102,HORTI FRUTI,BANANA PRATA KG,5.5,"2,10"
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2
3,104,HORTI,BATATA MONALISA KG,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,NaN,2.8
5,201,CARNES,PICANHA BOV RESFRIADA KG,79.9,42.0
6,202,CARNES,ALCATRA C/ MAMINHA KG,44.9,26.0
7,203,CARNES & AÇOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0
8,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0
9,204,CARNES,LINGUICA TOSCANA KG,22.9,12.0

----

### Lembre usar .str.upper() não .upper()
### DF_Cadastro['NOME_COLUNA'] precisa aponta -  se nao criar nova tabela apenas com coluan

--------

In [7]:
# REGRAS_PRODUTO = {
#     "  ":" ",
#     " ":"_",
#     "_PCA": "",
#     "_LATA": "",
#     "_CX": "",
#     "_KG": "",
#     "_kg": "",
#     "_UN": "",
#     "_un": "",
#     "_1L": "",
#     "_2L": "",
#     "_5L": "",
#     "_5KG": "",
#     "_1KG": "",
#     "_200G": "",
#     "_900ML": "",
#     "_350ML": "",
#     "_500G": "",
#     "_DE_": "",
# }

# silverCadastro["NOME_PRODUTO"] = (
#     silverCadastro["NOME_PRODUTO"]
#     .astype(str)
#     .str.replace(REGRAS_PRODUTO, regex=False)
# )

In [8]:
silverCadastro.head(5)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,TOMATE DEBORA KG,"7,90",3.2
1,102,HORTI FRUTI,BANANA PRATA KG,5.5,"2,10"
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2
3,104,HORTI,BATATA MONALISA KG,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,NaN,2.8

In [9]:
silverCadastro['CATEGORIA_BRUTA'].value_counts()

CATEGORIA_BRUTA
CARNES                4
HORTIFRUTI            3
BEBIDAS               3
FRIOS                 2
SECOS E MOLHADOS      2
PADARIA               2
HORTI FRUTI           1
HORTI                 1
CARNES & AÇOUGUE      1
FRIOS & LATICINIOS    1
LATICINIOS            1
SECOS                 1
MERCEARIA             1
Name: count, dtype: int64

# Criando regra ETL

----------------

In [10]:
REGRAS_CATEGORIA = {
    "FRIOS & LATICINIOS": "FRIOS E LATICINIOS",
    "FRIOS": "FRIOS E LATICINIOS",
    "LATICINIOS": "FRIOS E LATICINIOS",
    "SECOS E MOLHADOS": "SECOS E MOLHADOS",
    "SECOS": "SECOS E MOLHADOS",
    "MOLHADOS": "SECOS E MOLHADOS",
    "HORTI FRUTI": "HORTIFRUTI",
    "HORT": "HORTIFRUTI",
    "HORTI": "HORTIFRUTI",
    "CARNES": "ACOUGUE",
    "CARNES & AÇOUGUE": "ACOUGUE",
    "AÇOUGUE": "ACOUGUE",

}

silverCadastro["CATEGORIA_BRUTA"] = (
    silverCadastro["CATEGORIA_BRUTA"]
    .replace(REGRAS_CATEGORIA)
)

In [11]:
silverCadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,TOMATE DEBORA KG,"7,90",3.2
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,"2,10"
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,NaN,2.8
5,201,ACOUGUE,PICANHA BOV RESFRIADA KG,79.9,42.0
6,202,ACOUGUE,ALCATRA C/ MAMINHA KG,44.9,26.0
7,203,ACOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0
8,204,ACOUGUE,LINGUICA TOSCANA KG,22.9,12.0
9,204,ACOUGUE,LINGUICA TOSCANA KG,22.9,12.0

----

-----

In [12]:
silverCadastro = silverCadastro.drop_duplicates(subset='NOME_PRODUTO', keep='first')
assert silverCadastro['NOME_PRODUTO'].is_unique, "NOME_PRODUTO repetido no cadastro"

In [13]:
silverCadastro.head(25)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,TOMATE DEBORA KG,"7,90",3.2
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,"2,10"
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,NaN,2.8
5,201,ACOUGUE,PICANHA BOV RESFRIADA KG,79.9,42.0
6,202,ACOUGUE,ALCATRA C/ MAMINHA KG,44.9,26.0
7,203,ACOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0
8,204,ACOUGUE,LINGUICA TOSCANA KG,22.9,12.0
10,301,FRIOS E LATICINIOS,QUEIJO MUSSARELA PCA KG,42.9,26.0
11,302,FRIOS E LATICINIOS,PRESUNTO COZIDO KG,28.9,15.0
12,303,FRIOS E LATICINIOS,LEITE INTEGRAL 1L CX,5.29,3.4
13,304,FRIOS E LATICINIOS,REQUEIJAO CREMOS 200G,0.0,4.2
14,401,SECOS E MOLHADOS,ARROZ TIPO 1 5KG,25.9,18.5
15,402,SECOS E MOLHADOS,FEIJAO CARIOCA 1KG,6.99,4.1
16,403,SECOS E MOLHADOS,OLEO DE SOJA 900ML,6.49,4.5
17,404,MERCEARIA,CAFE TORRADO 500G,16.9,11.5
18,501,BEBIDAS,CERVEJA PILSEN LATA 350ML,3.89,2.2
19,502,BEBIDAS,REFRIGERANTE COLA 2L,8.49,4.8
20,503,BEBIDAS,SUCO CAIXINHA 1L,5.90,3.1
21,601,PADARIA,PAO FRANCES KG,13.9,4.0
22,602,PADARIA,BOLO CASEIRO UN,14.9,5.5

In [14]:
def clean_numeric_column(series: pd.Series) -> pd.Series:
    return pd.to_numeric(
        series.astype(str)
              .str.strip()
              .str.replace(',', '.', regex=False),
        errors='coerce'
    ).fillna(0.0)


silverCadastro['VENDA_CADASTRO'] = clean_numeric_column(silverCadastro['VALOR_VENDA_CADASTRO'])

silverCadastro['CUSTO_VENDA'] = clean_numeric_column(silverCadastro['CUSTO_CADASTRO'])

In [15]:
silverCadastro.head(6)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO,VENDA_CADASTRO,CUSTO_VENDA
0,101,HORTIFRUTI,TOMATE DEBORA KG,"7,90",3.2,7.9,3.2
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,"2,10",5.5,2.1
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2,3.5,1.2
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,NaN,2.8,0.0,2.8
5,201,ACOUGUE,PICANHA BOV RESFRIADA KG,79.9,42.0,79.9,42.0

In [16]:
silverCadastro = silverCadastro.drop(columns=['VALOR_VENDA_CADASTRO','CUSTO_CADASTRO'])

In [17]:
silverCadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA
0,101,HORTIFRUTI,TOMATE DEBORA KG,7.9,3.2
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,2.1
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,0.0,2.8
5,201,ACOUGUE,PICANHA BOV RESFRIADA KG,79.9,42.0
6,202,ACOUGUE,ALCATRA C/ MAMINHA KG,44.9,26.0
7,203,ACOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0
8,204,ACOUGUE,LINGUICA TOSCANA KG,22.9,12.0
10,301,FRIOS E LATICINIOS,QUEIJO MUSSARELA PCA KG,42.9,26.0

In [18]:
silverCadastro['MARGEM'] = silverCadastro['VENDA_CADASTRO'] - silverCadastro['CUSTO_VENDA']

In [19]:
silverCadastro.head()

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA,MARGEM
0,101,HORTIFRUTI,TOMATE DEBORA KG,7.9,3.2,4.7
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,2.1,3.4
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2,2.3
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5,3.4
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,0.0,2.8,-2.8

### CRIANDO NOVA TABELA COM MEDIDAS

In [20]:
silverCadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA,MARGEM
0,101,HORTIFRUTI,TOMATE DEBORA KG,7.9,3.2,4.7
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,2.1,3.4
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2,2.3
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5,3.4
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,0.0,2.8,-2.8
5,201,ACOUGUE,PICANHA BOV RESFRIADA KG,79.9,42.0,37.9
6,202,ACOUGUE,ALCATRA C/ MAMINHA KG,44.9,26.0,18.9
7,203,ACOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0,15.9
8,204,ACOUGUE,LINGUICA TOSCANA KG,22.9,12.0,10.9
10,301,FRIOS E LATICINIOS,QUEIJO MUSSARELA PCA KG,42.9,26.0,16.9

# Criando outra forma usar regra ETL

-------------

In [21]:
padrao = r'\b(\d+(?:[.,]\d+)?)?\s*(KG|G|MG|L|LT|ML|CM|CX|M|UN|PCA)\b'
       

silverCadastro[["PESO", "UNIDADE"]] = (
    silverCadastro["NOME_PRODUTO"]
    .str.extract(padrao, flags=re.IGNORECASE)
)

In [22]:
silverCadastro["NOME_PRODUTO"] = (
    silverCadastro["NOME_PRODUTO"]
    .str.replace(padrao, '', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

silverCadastro.head(5)

#### vt_Medida recebe tabela x vs_Medida recebe string com caminho da tabela

In [23]:
silverCadastro["PESO"] = pd.to_numeric(silverCadastro["PESO"].replace(np.nan, 1), errors='coerce')

In [24]:
silverCadastro["PESO"].head(5)

0    1
1    1
2    1
3    1
4    1
Name: PESO, dtype: int64

#### Localizado o erro, ao usar .replace com variavel vt_medid ele passar um string e não serie, isso causa um erro de tipo

-----

## Finalizado

In [29]:
SilverCadastro_ETL = silverCadastro

In [30]:
SilverCadastro_ETL.head(5)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA,MARGEM,PESO,UNIDADE
0,101,HORTIFRUTI,TOMATE DEBORA,7.9,3.2,4.7,1,KG
1,102,HORTIFRUTI,BANANA PRATA,5.5,2.1,3.4,1,KG
2,103,HORTIFRUTI,ALFACE AMERICANA,3.5,1.2,2.3,1,UN
3,104,HORTIFRUTI,BATATA MONALISA,5.9,2.5,3.4,1,KG
4,105,HORTIFRUTI,CEBOLA NACIONAL,0.0,2.8,-2.8,1,KG

In [34]:
resultado = False

In [35]:
def exportar_dados_excel(resultado):

    pasta = Path("..\\Raw\\table_silver\\")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "SilverCadastro_ETL.xlsx"


        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            SilverCadastro_ETL.to_excel(
                writer,
                sheet_name="xlsx",
                index=False
            )

        return True

    print("ERRO")
    return False

In [36]:
exportar_dados_excel(True)

True

### Esse comando salva o arquivo .xlsx