In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
DF_Vendas = pd.read_csv("..\\Raw\\RAW_VENDAS_POS.csv")

In [3]:
DF_Vendas.head(5)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA
0,900001,2026-01-01,CAIXA_PRINCIPAL,Juliana,503.00,5.00,3.94,19.70,FIADO_CADERNETO,CONCLUIDA
1,900002,2026-01-01,caixa 02,Patricia,NaN,2.00,34.47,68.94,FIADO_CADERNETO,CONCLUIDA
2,900003,2026-01-01,caixa 02,Patricia,404.00,4.00,32.32,129.28,FIADO_CADERNETO,CONCLUIDA
3,900004,2026-01-01,caixa 02,Patricia,303.00,4.00,36.05,144.20,CARTAO_CREDITO,CONCLUIDA
4,900005,2026-01-01,CX_02,Patricia,304.00,5.00,25.25,126.25,Cartao Debito,CONCLUIDA

----------

# ETL

### Padroniza Caixa

In [4]:
DF_Vendas['PDV_CAIXA'].value_counts()

PDV_CAIXA
caixa 02           3226
CAIXA_PRINCIPAL    3169
CAIXA 1            3152
CX_02              3145
CX_01              3130
Name: count, dtype: int64

In [5]:
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('caixa 02','CAIXA_02')
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('CAIXA_PRINCIPAL','CAIXA_P')
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('CAIXA 1','CAIXA_01')
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('CX_02','CAIXA_02')
DF_Vendas['PDV_CAIXA'] = DF_Vendas['PDV_CAIXA'].str.replace('CX_01','CAIXA_01')

In [6]:
DF_Vendas['PDV_CAIXA'].value_counts()

PDV_CAIXA
CAIXA_02    6371
CAIXA_01    6282
CAIXA_P     3169
Name: count, dtype: int64

In [7]:
DF_Vendas.head(3)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA
0,900001,2026-01-01,CAIXA_P,Juliana,503.00,5.00,3.94,19.70,FIADO_CADERNETO,CONCLUIDA
1,900002,2026-01-01,CAIXA_02,Patricia,NaN,2.00,34.47,68.94,FIADO_CADERNETO,CONCLUIDA
2,900003,2026-01-01,CAIXA_02,Patricia,404.00,4.00,32.32,129.28,FIADO_CADERNETO,CONCLUIDA

-----

### Trata nulos

In [8]:
DF_Vendas['COD_PRODUTO'].dtype

dtype('float64')

In [9]:
DF_Vendas['COD_PRODUTO'].isna().value_counts() # Limpa nulos e substitui 1000001

COD_PRODUTO
False    15168
True       654
Name: count, dtype: int64

In [10]:
DF_Vendas['COD_PRODUTO'].value_counts()

COD_PRODUTO
102.00    684
403.00    680
302.00    672
104.00    667
201.00    661
105.00    659
0.00      652
401.00    650
501.00    645
999.00    643
103.00    632
301.00    631
303.00    627
101.00    623
202.00    620
203.00    619
503.00    614
502.00    608
304.00    607
204.00    606
601.00    602
602.00    601
402.00    600
404.00    565
Name: count, dtype: int64

### Verifica NULL

In [11]:
DF_Vendas['ID_TRANSACAO'].isna().value_counts()

ID_TRANSACAO
False    15822
Name: count, dtype: int64

In [12]:
DF_Vendas['PDV_CAIXA'].isna().value_counts() # Limpa nulos e substitui 1000001

PDV_CAIXA
False    15822
Name: count, dtype: int64

In [13]:
DF_Vendas['OPERADOR'].isna().value_counts() # Limpa nulos e substitui 1000001

OPERADOR
False    15555
True       267
Name: count, dtype: int64

In [14]:
DF_Vendas['COD_PRODUTO'].isna().value_counts() # Limpa nulos e substitui 1000001

COD_PRODUTO
False    15168
True       654
Name: count, dtype: int64

In [15]:
DF_Vendas['QTD_VENDIDA'].isna().value_counts() # Limpa nulos e substitui 1000001

QTD_VENDIDA
False    15822
Name: count, dtype: int64

In [16]:
DF_Vendas['PRECO_UNIT_COBRADO'].isna().value_counts() # Limpa nulos e substitui 1000001

PRECO_UNIT_COBRADO
False    15822
Name: count, dtype: int64

In [17]:
DF_Vendas['TOTAL_PAGO'].isna().value_counts() # Limpa nulos e substitui 1000001

TOTAL_PAGO
False    15822
Name: count, dtype: int64

In [18]:
DF_Vendas['FORMA_PAGTO'].isna().value_counts() # Limpa nulos e substitui 1000001

FORMA_PAGTO
False    13826
True      1996
Name: count, dtype: int64

In [19]:
DF_Vendas['STATUS_VENDA'].isna().value_counts() # Limpa nulos

STATUS_VENDA
False    15822
Name: count, dtype: int64

In [20]:
DF_Vendas.head(3)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA
0,900001,2026-01-01,CAIXA_P,Juliana,503.00,5.00,3.94,19.70,FIADO_CADERNETO,CONCLUIDA
1,900002,2026-01-01,CAIXA_02,Patricia,NaN,2.00,34.47,68.94,FIADO_CADERNETO,CONCLUIDA
2,900003,2026-01-01,CAIXA_02,Patricia,404.00,4.00,32.32,129.28,FIADO_CADERNETO,CONCLUIDA

### Padroniza Operador

In [21]:
DF_Vendas['OPERADOR'] = DF_Vendas['OPERADOR'].fillna('DESCONHECIDO')
DF_Vendas['OPERADOR'] = DF_Vendas['OPERADOR'].str.replace('Carlos (Gerente)','Carlos_Ger')
DF_Vendas['OPERADOR'] = DF_Vendas['OPERADOR'].str.replace('SISTEMA','N_IDENTIFICADO')
DF_Vendas['OPERADOR'] = DF_Vendas['OPERADOR'].str.upper()
DF_Vendas['OPERADOR'].value_counts()

OPERADOR
JULIANA           8950
PATRICIA          6012
CARLOS_GER         309
N_IDENTIFICADO     284
DESCONHECIDO       267
Name: count, dtype: int64

In [22]:
DF_Vendas['OPERADOR'].value_counts()

OPERADOR
JULIANA           8950
PATRICIA          6012
CARLOS_GER         309
N_IDENTIFICADO     284
DESCONHECIDO       267
Name: count, dtype: int64

In [23]:
DF_Vendas['TOTAL_PAGO'].sum()

np.float64(645052.34)

### Status vendas

In [24]:
DF_Vendas['STATUS_VENDA'].value_counts()

STATUS_VENDA
CONCLUIDA    9051
ESTORNADA    2298
EM_ABERTO    2247
CANCELADA    2226
Name: count, dtype: int64

In [25]:
DF_Vendas['STATUS_VENDA'].count()

np.int64(15822)

In [26]:
DF_Vendas['STATUS_VENDA'] = DF_Vendas['STATUS_VENDA'].str.replace('EM_ABERTO','ABERTO')

In [27]:
DF_Vendas['STATUS_VENDA'].value_counts()

STATUS_VENDA
CONCLUIDA    9051
ESTORNADA    2298
ABERTO       2247
CANCELADA    2226
Name: count, dtype: int64

### Padroniza pagamentos

In [28]:
DF_Vendas['FORMA_PAGTO'].value_counts() #Antes ajuste

FORMA_PAGTO
FIADO_CADERNETO    2062
Cartao Debito      2018
DIVERSOS           1991
Pix                1959
DINHEIRO           1942
PIX                1933
CARTAO_CREDITO     1921
Name: count, dtype: int64

In [29]:
# Realiza modificacoes
DF_Vendas['FORMA_PAGTO'] = DF_Vendas['FORMA_PAGTO'].fillna('INDEFINIDO')
DF_Vendas['FORMA_PAGTO'] = DF_Vendas['FORMA_PAGTO'].str.replace('Cartao Debito','CARTAO_DEB')
DF_Vendas['FORMA_PAGTO'] = DF_Vendas['FORMA_PAGTO'].str.replace('DIVERSOS','MISTO')
DF_Vendas['FORMA_PAGTO'] = DF_Vendas['FORMA_PAGTO'].str.replace('Pix','PIX')
DF_Vendas['FORMA_PAGTO'] = DF_Vendas['FORMA_PAGTO'].str.replace('CARTAO_CREDITO','CARTAO_CRED')

In [30]:
DF_Vendas['FORMA_PAGTO'].value_counts() #depois ajuste

FORMA_PAGTO
PIX                3892
FIADO_CADERNETO    2062
CARTAO_DEB         2018
INDEFINIDO         1996
MISTO              1991
DINHEIRO           1942
CARTAO_CRED        1921
Name: count, dtype: int64

## Padroniza Produtos

In [31]:
DF_Vendas['COD_PRODUTO'] = DF_Vendas['COD_PRODUTO'].fillna(1000001).astype('Int64')

In [32]:
DF_Vendas['COD_PRODUTO'] = DF_Vendas['COD_PRODUTO'].replace(0 , 1000001) # Limpa 0 e substitui 1000001

In [33]:
DF_Vendas.head(5)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA
0,900001,2026-01-01,CAIXA_P,JULIANA,503,5.00,3.94,19.70,FIADO_CADERNETO,CONCLUIDA
1,900002,2026-01-01,CAIXA_02,PATRICIA,1000001,2.00,34.47,68.94,FIADO_CADERNETO,CONCLUIDA
2,900003,2026-01-01,CAIXA_02,PATRICIA,404,4.00,32.32,129.28,FIADO_CADERNETO,CONCLUIDA
3,900004,2026-01-01,CAIXA_02,PATRICIA,303,4.00,36.05,144.20,CARTAO_CRED,CONCLUIDA
4,900005,2026-01-01,CAIXA_02,PATRICIA,304,5.00,25.25,126.25,CARTAO_DEB,CONCLUIDA

### Ajusta Data

In [34]:
# # Cria coluna Data
# DF_Vendas['DATA'] = pd.to_datetime(DF_Vendas['DATA_HORA_VENDA'], format="mixed")

# # cria colunas Mes e Ano
# DF_Vendas['MES'] = DF_Vendas['DATA'].dt.month
# DF_Vendas['ANO'] = DF_Vendas['DATA'].dt.year

# # deleta coluna DATA_HORA_VENDA
# DF_Vendas = DF_Vendas.drop(columns={'DATA'})

# DF_Vendas.head(5)

d_iso = pd.to_datetime(DF_Vendas['DATA_HORA_VENDA'], format='%Y-%m-%d', errors='coerce')
d_br_hm = pd.to_datetime(DF_Vendas['DATA_HORA_VENDA'], format='%d/%m/%Y %H:%M', errors='coerce')
d_br = pd.to_datetime(DF_Vendas['DATA_HORA_VENDA'], format='%d/%m/%Y', errors='coerce')

DF_Vendas['DATA'] = d_iso.fillna(d_br_hm).fillna(d_br)
assert DF_Vendas['DATA'].notna().all(), "existe data fora dos três formatos"

DF_Vendas['ANO'] = DF_Vendas['DATA'].dt.year
DF_Vendas['MES'] = DF_Vendas['DATA'].dt.month
DF_Vendas['DIA'] = DF_Vendas['DATA'].dt.day

### Validacao Valores de venda total

In [35]:
DF_Vendas['VENDAS_TOTAL'] = (DF_Vendas['QTD_VENDIDA'] * DF_Vendas['PRECO_UNIT_COBRADO']).round(2)
DF_Vendas['DIF_VENDA'] = (DF_Vendas['TOTAL_PAGO'] - DF_Vendas['VENDAS_TOTAL']).round(2)

In [36]:
check = (DF_Vendas['QTD_VENDIDA'] * DF_Vendas['PRECO_UNIT_COBRADO'] - DF_Vendas['TOTAL_PAGO']).round(2)
print("fórmula confere:", (check == DF_Vendas['DIF_VENDA'].round(2)).all())

fórmula confere: False

In [37]:
zerados = DF_Vendas['TOTAL_PAGO'] == 0

print(DF_Vendas.loc[zerados, 'STATUS_VENDA'].value_counts())
print("DIF = -VENDAS_TOTAL onde TOTAL_PAGO é 0:",
      np.isclose(DF_Vendas.loc[zerados, 'DIF_VENDA'],
                 -DF_Vendas.loc[zerados, 'VENDAS_TOTAL']).all())

STATUS_VENDA
ESTORNADA    2298
ABERTO       2247
CANCELADA    2226
Name: count, dtype: int64
DIF = -VENDAS_TOTAL onde TOTAL_PAGO é 0: True

In [38]:
diff = (check - DF_Vendas['DIF_VENDA']).abs()

print("maior diferença:", diff.max())

maior diferença: 448.4

In [39]:
conc = DF_Vendas[DF_Vendas['STATUS_VENDA'] == 'CONCLUIDA']
print("CONCLUIDA com DIF_VENDA > R$ 0,01:", (conc['DIF_VENDA'].abs() > 0.01).sum())

CONCLUIDA com DIF_VENDA > R$ 0,01: 0

In [40]:
DF_Concluidas = DF_Vendas[DF_Vendas['STATUS_VENDA'] == 'CONCLUIDA'].copy()

print("linhas concluídas:", len(DF_Concluidas))
print("faturamento:", round(DF_Concluidas['TOTAL_PAGO'].sum(), 2))

linhas concluídas: 9051
faturamento: 645052.34

In [41]:
DF_Vendas.head(5)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA,DATA,ANO,MES,DIA,VENDAS_TOTAL,DIF_VENDA
0,900001,2026-01-01,CAIXA_P,JULIANA,503,5.00,3.94,19.70,FIADO_CADERNETO,CONCLUIDA,2026-01-01,2026,1,1,19.70,0.00
1,900002,2026-01-01,CAIXA_02,PATRICIA,1000001,2.00,34.47,68.94,FIADO_CADERNETO,CONCLUIDA,2026-01-01,2026,1,1,68.94,0.00
2,900003,2026-01-01,CAIXA_02,PATRICIA,404,4.00,32.32,129.28,FIADO_CADERNETO,CONCLUIDA,2026-01-01,2026,1,1,129.28,0.00
3,900004,2026-01-01,CAIXA_02,PATRICIA,303,4.00,36.05,144.20,CARTAO_CRED,CONCLUIDA,2026-01-01,2026,1,1,144.20,0.00
4,900005,2026-01-01,CAIXA_02,PATRICIA,304,5.00,25.25,126.25,CARTAO_DEB,CONCLUIDA,2026-01-01,2026,1,1,126.25,0.00

In [42]:
DF_Vendas['DIF_VENDA'].value_counts()

DIF_VENDA
0.00       11277
-33.00         5
-26.10         5
-32.28         4
-29.30         4
           ...
-145.24        1
-37.05         1
-107.08        1
-110.28        1
-173.12        1
Name: count, Length: 3665, dtype: int64

-----

# SALVAR

In [43]:
resultado = False

In [44]:
silverVendas_ETL = DF_Vendas

In [45]:
def export_dados_excel(resultado):

    pasta = Path("..\\Raw\\table_silver\\")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "silverVendas_ETL.xlsx"

        # 1. Criar os arquivos
        silverVendas_ETL.to_excel(arquivo_excel, index=False)


        # 3. Consolidar em um Excel com duas abas
        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            silverVendas_ETL.to_excel(
                writer,
                sheet_name="Excel",
                index=False
            )


        return True

    print("ERRO")
    return False

In [46]:
export_dados_excel(True)

True