In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
DF_Compras = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\NewStudy_04-10\\RAW_COMPRAS_ENTRADAS.csv")

In [3]:
DF_Compras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO
0,NF-1006,01/01/2026,CEASA SP - PRODUTORES UNIDOS,101,55,163.39,Mateus
1,NF-1046,01/01/2026,CEASA SP - PRODUTORES UNIDOS,102,119,335.78,Thiago
2,NF-1018,01/01/2026,CEASA SP - PRODUTORES UNIDOS,103,115 KG,243.92,Thiago
3,NF-1013,01/01/2026,CEASA SP - PRODUTORES UNIDOS,104,41,123.78,diego
4,NF-1004,01/01/2026,CEASA SP - PRODUTORES UNIDOS,105,85,235.48,Diego

-----

In [4]:
silverCompras = DF_Compras # Instancia tabela compras

In [5]:
silverCompras['N_NF'] = silverCompras['NUM_NOTA_FISCAL'].str.replace('NF-','')

In [6]:
silverCompras['FORNECEDOR'].value_counts()

FORNECEDOR
CEASA SP - PRODUTORES UNIDOS     242
FRIGORIFICO FRIBOI / BOI LEVE    160
Name: count, dtype: int64

In [19]:
silverCompras['FORNECEDOR'] = silverCompras['FORNECEDOR'].str.replace(' - PRODUTORES UNIDOS','')

In [20]:
silverCompras['FORNECEDOR'] = silverCompras['FORNECEDOR'].str.replace(' / BOI LEVE','')

In [21]:
silverCompras['QTD_COMPRADA'] = silverCompras['QTD_COMPRADA'].str.replace('KG','')

In [22]:
silverCompras['VALOR_TOTAL_NOTA'] = silverCompras['VALOR_TOTAL_NOTA'].str.replace(',','.')

In [23]:
silverCompras['TOTAL_NOTA'] = pd.to_numeric(silverCompras['VALOR_TOTAL_NOTA'], errors="coerce")

-----

In [12]:
silverCompras['RESPONSAVEL_RECEBIMENTO'] = silverCompras['RESPONSAVEL_RECEBIMENTO'].str.upper()

In [13]:
silverCompras['DATA'] = pd.to_datetime(silverCompras['DATA_ENTRADA'], format='%d/%m/%Y')

silverCompras['MES'] = silverCompras['DATA'].dt.month
silverCompras['ANO'] = silverCompras['DATA'].dt.year

In [14]:

DF_Compras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO,N_NF,TOTAL_NOTA,DATA,MES,ANO
0,NF-1006,01/01/2026,CEASA SP,101,55,163.39,MATEUS,1006,163.39,2026-01-01,1,2026
1,NF-1046,01/01/2026,CEASA SP,102,119,335.78,THIAGO,1046,335.78,2026-01-01,1,2026
2,NF-1018,01/01/2026,CEASA SP,103,115,243.92,THIAGO,1018,243.92,2026-01-01,1,2026
3,NF-1013,01/01/2026,CEASA SP,104,41,123.78,DIEGO,1013,123.78,2026-01-01,1,2026
4,NF-1004,01/01/2026,CEASA SP,105,85,235.48,DIEGO,1004,235.48,2026-01-01,1,2026

------

In [15]:
resultado = True

In [16]:
silverCompras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO,N_NF,TOTAL_NOTA,DATA,MES,ANO
0,NF-1006,01/01/2026,CEASA SP,101,55,163.39,MATEUS,1006,163.39,2026-01-01,1,2026
1,NF-1046,01/01/2026,CEASA SP,102,119,335.78,THIAGO,1046,335.78,2026-01-01,1,2026
2,NF-1018,01/01/2026,CEASA SP,103,115,243.92,THIAGO,1018,243.92,2026-01-01,1,2026
3,NF-1013,01/01/2026,CEASA SP,104,41,123.78,DIEGO,1013,123.78,2026-01-01,1,2026
4,NF-1004,01/01/2026,CEASA SP,105,85,235.48,DIEGO,1004,235.48,2026-01-01,1,2026

In [17]:
def export_dados_excel(resultado):

    pasta = Path(r"C:\Users\Public\Teste_Jupyter\Mercado\2 - Silver")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "silverCompras_ETL.xlsx"

        # 1. Criar os arquivos
        silverCompras.to_excel(arquivo_excel, index=False)

        # 3. Consolidar em um Excel com duas abas
        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            silverCompras.to_excel(
                writer,
                sheet_name="Excel",
                index=False
            )

        return True

    print("ERRO")
    return False

In [18]:
export_dados_excel(resultado)

True