## Inicializa o principais dependencias

In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
silverVendas = pd.read_excel("..\\Raw\\table_silver\\SilverVendas_ETL.xlsx")

In [3]:
silverVendas['OPERADOR'].value_counts()

OPERADOR
JULIANA           8950
PATRICIA          6012
CARLOS_GER         309
N_IDENTIFICADO     284
DESCONHECIDO       267
Name: count, dtype: int64

In [4]:
silverVendas['COD_PRODUTO'].duplicated().value_counts() # Valida quanto produtos repeditos

COD_PRODUTO
True     15798
False       24
Name: count, dtype: int64

In [5]:
silverVendas['ID_TRANSACAO'].duplicated().value_counts()

ID_TRANSACAO
False    15822
Name: count, dtype: int64

In [6]:
silverVendas['COD_PRODUTO'].isna().value_counts()

COD_PRODUTO
False    15822
Name: count, dtype: int64

In [7]:
silverVendas['COD_PRODUTO'].value_counts()

COD_PRODUTO
1000001    1306
102         684
403         680
302         672
104         667
201         661
105         659
401         650
501         645
999         643
103         632
301         631
303         627
101         623
202         620
203         619
503         614
502         608
304         607
204         606
601         602
602         601
402         600
404         565
Name: count, dtype: int64

-------

------

In [8]:
silverVendas.head(5)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA,MES,ANO,VENDAS_TOTAL,DIF_VENDA
0,900001,2026-01-01,CAIXA_P,JULIANA,503,5,3.94,19.70,FIADO_CADERNETO,CONCLUIDA,1,2026,19.70,0.0
1,900002,2026-01-01,CAIXA_02,PATRICIA,1000001,2,34.47,68.94,FIADO_CADERNETO,CONCLUIDA,1,2026,68.94,0.0
2,900003,2026-01-01,CAIXA_02,PATRICIA,404,4,32.32,129.28,FIADO_CADERNETO,CONCLUIDA,1,2026,129.28,0.0
3,900004,2026-01-01,CAIXA_02,PATRICIA,303,4,36.05,144.20,CARTAO_CRED,CONCLUIDA,1,2026,144.20,0.0
4,900005,2026-01-01,CAIXA_02,PATRICIA,304,5,25.25,126.25,CARTAO_DEB,CONCLUIDA,1,2026,126.25,0.0

# CRIA NOVAS TABELAS

### Agrupa por ID

In [9]:
g_id = silverVendas.groupby('ID_TRANSACAO', as_index=False).agg(
    TRANSACAO = ('ID_TRANSACAO', 'nunique'),
    QTD_VENDIDA = ('QTD_VENDIDA', 'sum'),
    FATURAMENTO = ('VENDAS_TOTAL', 'sum'),
)

In [10]:
g_id.head(3)

   ID_TRANSACAO  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0        900001          1            5        19.70
1        900002          1            2        68.94
2        900003          1            4       129.28

-------

### Agrupa por Caixa

In [11]:
g_cx = silverVendas.groupby('PDV_CAIXA', as_index=False).agg(
    TRANSACAO = ('ID_TRANSACAO', 'nunique'),
    QTD_VENDIDA = ('QTD_VENDIDA', 'sum'),
    FATURAMENTO = ('VENDAS_TOTAL', 'sum'),
)

In [12]:
g_cx.head(3)

  PDV_CAIXA  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0  CAIXA_01       6282        18793    378501.13
1  CAIXA_02       6371        19042    388118.81
2   CAIXA_P       3169         9589    196993.85

----

### Operdor

In [13]:
g_op = silverVendas.groupby('OPERADOR', as_index=False).agg(
    TRANSACAO = ('ID_TRANSACAO', 'nunique'),
    QTD_VENDIDA = ('QTD_VENDIDA', 'sum'),
    FATURAMENTO = ('VENDAS_TOTAL', 'sum'),
)

In [14]:
g_op.head(3)

       OPERADOR  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0    CARLOS_GER        309          933     19063.71
1  DESCONHECIDO        267          816     16719.05
2       JULIANA       8950        26862    544227.60

----

### Cod_Produto

In [15]:
g_cod = silverVendas.groupby('COD_PRODUTO', as_index=False).agg(
    TRANSACAO = ('ID_TRANSACAO', 'nunique'),
    QTD_VENDIDA = ('QTD_VENDIDA', 'sum'),
    FATURAMENTO = ('VENDAS_TOTAL', 'sum'),
)

In [16]:
g_cod.head(3)

   COD_PRODUTO  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0          101        623         1890     38872.49
1          102        684         2067     43207.28
2          103        632         1831     37718.64

----

### Forma pag

In [17]:
g_fpagamento = silverVendas.groupby('FORMA_PAGTO', as_index=False).agg(
    TRANSACAO = ('ID_TRANSACAO', 'nunique'),
    QTD_VENDIDA = ('QTD_VENDIDA', 'sum'),
    FATURAMENTO = ('VENDAS_TOTAL', 'sum'),
)

In [18]:
g_fpagamento.head(3)

   FORMA_PAGTO  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0  CARTAO_CRED       1921         5819    118936.71
1   CARTAO_DEB       2018         6143    126883.67
2     DINHEIRO       1942         5833    119820.12

----

### Status

In [19]:
g_status = silverVendas.groupby('STATUS_VENDA', as_index=False).agg(
      TRANSACOES=('ID_TRANSACAO', 'nunique'),
      QTD_VENDIDA=('QTD_VENDIDA', 'sum'),
      FATURAMENTO_BRUTO=('VENDAS_TOTAL', 'sum'),
)

In [20]:
g_status.head(3)

  STATUS_VENDA  TRANSACOES  QTD_VENDIDA  FATURAMENTO_BRUTO
0       ABERTO        2247         6748          158608.15
1    CANCELADA        2226         6525               0.00
2    CONCLUIDA        9051        27302          645052.34

----

### Ano

In [21]:
g_ano = silverVendas.groupby('STATUS_VENDA', as_index=False).agg(
    TRANSACAO = ('ID_TRANSACAO', 'nunique'),
    QTD_VENDIDA = ('QTD_VENDIDA', 'sum'),
    FATURAMENTO = ('VENDAS_TOTAL', 'sum'),
)

In [22]:
g_ano.head(3)

  STATUS_VENDA  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0       ABERTO       2247         6748    158608.15
1    CANCELADA       2226         6525         0.00
2    CONCLUIDA       9051        27302    645052.34

----

### Mes

In [23]:
g_mes = silverVendas.groupby('MES', as_index=False).agg(
    TRANSACAO = ('ID_TRANSACAO', 'nunique'),
    QTD_VENDIDA = ('QTD_VENDIDA', 'sum'),
    FATURAMENTO = ('VENDAS_TOTAL', 'sum'),
)
g_mes.head(3)

   MES  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0    1       4407        13150    266736.43
1    2       3794        11394    231696.82
2    3       4550        13656    278978.20

----

In [24]:
silverVendas['COD_PRODUTO'].isna().value_counts()

COD_PRODUTO
False    15822
Name: count, dtype: int64

In [25]:
  print(g_mes)
  assert abs(g_mes['FATURAMENTO'].sum() - silverVendas['VENDAS_TOTAL'].sum()) < 0.01

    MES  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0     1       4407        13150    266736.43
1     2       3794        11394    231696.82
2     3       4550        13656    278978.20
3     4        355         1077     22544.63
4     5        359         1072     21229.82
5     6        349         1059     21862.65
6     7        361         1111     22136.82
7     8        301          889     17301.17
8     9        337         1012     21080.79
9    10        329          959     19842.76
10   11        341         1006     20496.48
11   12        339         1039     19707.22

----

In [26]:
# cria tabela, agrupa por operador com agregaçãodos id
g_op_x_id = (
    silverVendas
    .groupby('OPERADOR', as_index=False)['ID_TRANSACAO']
    .sum()
)
g_op_x_id.head(10)

         OPERADOR  ID_TRANSACAO
0      CARLOS_GER     280510519
1    DESCONHECIDO     242272139
2         JULIANA    8125314984
3  N_IDENTIFICADO     257931850
4        PATRICIA    5458946261

In [27]:
# cria tabela, agrupa por codigo produto com agregaçãodos id
g_cod_x_id = (
    silverVendas
    .groupby('COD_PRODUTO', as_index=False)['QTD_VENDIDA']
    .sum()
)

g_cod_x_id.head(5)

   COD_PRODUTO  QTD_VENDIDA
0          101         1890
1          102         2067
2          103         1831
3          104         2026
4          105         1953

In [28]:
g_cod_x_id['COD_PRODUTO'].value_counts()

COD_PRODUTO
101        1
102        1
103        1
104        1
105        1
201        1
202        1
203        1
204        1
301        1
302        1
303        1
304        1
401        1
402        1
403        1
404        1
501        1
502        1
503        1
601        1
602        1
999        1
1000001    1
Name: count, dtype: int64

In [29]:
# cria tabela, agrupa por forma com agregaçãodos Qtd vendida
g_form_x_cx = (
    silverVendas
    .groupby('FORMA_PAGTO', as_index=False)['QTD_VENDIDA']
    .count()
)

g_form_x_cx.head(5)

       FORMA_PAGTO  QTD_VENDIDA
0      CARTAO_CRED         1921
1       CARTAO_DEB         2018
2         DINHEIRO         1942
3  FIADO_CADERNETO         2062
4       INDEFINIDO         1996

In [30]:
# cria tabela, agrupa por status com agregaçãodos qt vendas
g_status_x_cod = (
    silverVendas
    .groupby('STATUS_VENDA', as_index=False)['QTD_VENDIDA']
    .count()
)

g_status_x_cod.head(5)

  STATUS_VENDA  QTD_VENDIDA
0       ABERTO         2247
1    CANCELADA         2226
2    CONCLUIDA         9051
3    ESTORNADA         2298

In [31]:
# cria tabela, agrupa por CX com agregaçãodos qtd vendida
g_status_x_unid = (
    silverVendas
    .groupby('PDV_CAIXA', as_index=False)['QTD_VENDIDA']
    .count()
)

g_status_x_unid.head(10)

  PDV_CAIXA  QTD_VENDIDA
0  CAIXA_01         6282
1  CAIXA_02         6371
2   CAIXA_P         3169

In [32]:
# cria tabela, agrupa por operador com agregaçãodos outros dados
g_op_x_agg = (
    silverVendas
    .groupby('OPERADOR')
    .agg(
    TOTAL=('TOTAL_PAGO', 'sum'),
    MEDIA=('TOTAL_PAGO', 'mean'),
    QUANTIDADE=('QTD_VENDIDA', 'count'),
    COD_PRODUTOS=('ID_TRANSACAO', 'nunique')
)
)

g_op_x_agg.head(10)

                    TOTAL      MEDIA  QUANTIDADE  COD_PRODUTOS
OPERADOR
CARLOS_GER       12033.08  38.942006         309           309
DESCONHECIDO     10760.96  40.303221         267           267
JULIANA         362366.23  40.487847        8950          8950
N_IDENTIFICADO   10741.34  37.821620         284           284
PATRICIA        249150.73  41.442237        6012          6012

# Resumo Tabelas

In [33]:
g_id.head(3)

   ID_TRANSACAO  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0        900001          1            5        19.70
1        900002          1            2        68.94
2        900003          1            4       129.28

In [34]:
g_cx.head(3)

  PDV_CAIXA  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0  CAIXA_01       6282        18793    378501.13
1  CAIXA_02       6371        19042    388118.81
2   CAIXA_P       3169         9589    196993.85

In [35]:
g_op.head(3)

       OPERADOR  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0    CARLOS_GER        309          933     19063.71
1  DESCONHECIDO        267          816     16719.05
2       JULIANA       8950        26862    544227.60

In [36]:
g_cod.head(3)

   COD_PRODUTO  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0          101        623         1890     38872.49
1          102        684         2067     43207.28
2          103        632         1831     37718.64

In [37]:
g_fpagamento.head(3)

   FORMA_PAGTO  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0  CARTAO_CRED       1921         5819    118936.71
1   CARTAO_DEB       2018         6143    126883.67
2     DINHEIRO       1942         5833    119820.12

In [38]:
g_status.head(3)

  STATUS_VENDA  TRANSACOES  QTD_VENDIDA  FATURAMENTO_BRUTO
0       ABERTO        2247         6748          158608.15
1    CANCELADA        2226         6525               0.00
2    CONCLUIDA        9051        27302          645052.34

In [39]:
g_ano.head(3)

  STATUS_VENDA  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0       ABERTO       2247         6748    158608.15
1    CANCELADA       2226         6525         0.00
2    CONCLUIDA       9051        27302    645052.34

In [40]:
g_mes.head(3)

   MES  TRANSACAO  QTD_VENDIDA  FATURAMENTO
0    1       4407        13150    266736.43
1    2       3794        11394    231696.82
2    3       4550        13656    278978.20

In [41]:
g_mes['FATURAMENTO'].sum()

np.float64(963613.79)

----

In [42]:
g_vendas_h = pd.concat(
    [g_id,g_cod,g_cx,g_op,g_fpagamento,g_status,g_ano,g_mes], axis=1
)
g_vendas_h.head(5)

,ID_TRANSACAO,TRANSACAO,QTD_VENDIDA,FATURAMENTO,COD_PRODUTO,TRANSACAO,QTD_VENDIDA,FATURAMENTO,PDV_CAIXA,TRANSACAO,...,QTD_VENDIDA,FATURAMENTO_BRUTO,STATUS_VENDA,TRANSACAO,QTD_VENDIDA,FATURAMENTO,MES,TRANSACAO,QTD_VENDIDA,FATURAMENTO
0,900001,1,5,19.70,101.0,623.0,1890.0,38872.49,CAIXA_01,6282.0,...,6748.0,158608.15,ABERTO,2247.0,6748.0,158608.15,1.0,4407.0,13150.0,266736.43
1,900002,1,2,68.94,102.0,684.0,2067.0,43207.28,CAIXA_02,6371.0,...,6525.0,0.00,CANCELADA,2226.0,6525.0,0.00,2.0,3794.0,11394.0,231696.82
2,900003,1,4,129.28,103.0,632.0,1831.0,37718.64,CAIXA_P,3169.0,...,27302.0,645052.34,CONCLUIDA,9051.0,27302.0,645052.34,3.0,4550.0,13656.0,278978.20
3,900004,1,4,144.20,104.0,667.0,2026.0,40813.40,NaN,NaN,...,6849.0,159953.30,ESTORNADA,2298.0,6849.0,159953.30,4.0,355.0,1077.0,22544.63
4,900005,1,5,126.25,105.0,659.0,1953.0,41976.44,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,359.0,1072.0,21229.82

In [43]:
g_vendas_h.count()

ID_TRANSACAO         15822
TRANSACAO            15822
QTD_VENDIDA          15822
FATURAMENTO          15822
COD_PRODUTO             24
TRANSACAO               24
QTD_VENDIDA             24
FATURAMENTO             24
PDV_CAIXA                3
TRANSACAO                3
QTD_VENDIDA              3
FATURAMENTO              3
OPERADOR                 5
TRANSACAO                5
QTD_VENDIDA              5
FATURAMENTO              5
FORMA_PAGTO              7
TRANSACAO                7
QTD_VENDIDA              7
FATURAMENTO              7
STATUS_VENDA             4
TRANSACOES               4
QTD_VENDIDA              4
FATURAMENTO_BRUTO        4
STATUS_VENDA             4
TRANSACAO                4
QTD_VENDIDA              4
FATURAMENTO              4
MES                     12
TRANSACAO               12
QTD_VENDIDA             12
FATURAMENTO             12
dtype: int64

In [44]:
g_vendas_v = pd.concat(
    [g_id,g_cod,g_cx,g_op,g_fpagamento,g_status,g_ano,g_mes], axis=0
)
g_vendas_v.head(5)

,ID_TRANSACAO,TRANSACAO,QTD_VENDIDA,FATURAMENTO,COD_PRODUTO,PDV_CAIXA,OPERADOR,FORMA_PAGTO,STATUS_VENDA,TRANSACOES,FATURAMENTO_BRUTO,MES
0,900001.0,1.0,5,19.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,900002.0,1.0,2,68.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,900003.0,1.0,4,129.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,900004.0,1.0,4,144.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,900005.0,1.0,5,126.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
g_vendas_v.count()

ID_TRANSACAO         15822
TRANSACAO            15877
QTD_VENDIDA          15881
FATURAMENTO          15877
COD_PRODUTO             24
PDV_CAIXA                3
OPERADOR                 5
FORMA_PAGTO              7
STATUS_VENDA             8
TRANSACOES               4
FATURAMENTO_BRUTO        4
MES                     12
dtype: int64

In [46]:
g_vendas_keys = pd.concat(
    [g_id,g_cod,g_cx,g_op,g_fpagamento,g_status,g_ano,g_mes], keys=["id", "cod", "cx", "op", "fpagamento", "status", "ano", "mes"]
)
g_vendas_keys.head(5)

      ID_TRANSACAO  TRANSACAO  QTD_VENDIDA  FATURAMENTO  COD_PRODUTO  \
id 0      900001.0        1.0            5        19.70          NaN
   1      900002.0        1.0            2        68.94          NaN
   2      900003.0        1.0            4       129.28          NaN
   3      900004.0        1.0            4       144.20          NaN
   4      900005.0        1.0            5       126.25          NaN

     PDV_CAIXA OPERADOR FORMA_PAGTO STATUS_VENDA  TRANSACOES  \
id 0       NaN      NaN         NaN          NaN         NaN
   1       NaN      NaN         NaN          NaN         NaN
   2       NaN      NaN         NaN          NaN         NaN
   3       NaN      NaN         NaN          NaN         NaN
   4       NaN      NaN         NaN          NaN         NaN

      FATURAMENTO_BRUTO  MES
id 0                NaN  NaN
   1                NaN  NaN
   2                NaN  NaN
   3                NaN  NaN
   4                NaN  NaN

In [47]:
g_vendas_keys.count()

ID_TRANSACAO         15822
TRANSACAO            15877
QTD_VENDIDA          15881
FATURAMENTO          15877
COD_PRODUTO             24
PDV_CAIXA                3
OPERADOR                 5
FORMA_PAGTO              7
STATUS_VENDA             8
TRANSACOES               4
FATURAMENTO_BRUTO        4
MES                     12
dtype: int64

In [48]:
diverg = silverVendas.assign(
    DIVERGE=(silverVendas['QTD_VENDIDA'] * silverVendas['PRECO_UNIT_COBRADO'] - silverVendas['TOTAL_PAGO']).abs() > 0.01
)
print(diverg)
print(diverg.groupby('STATUS_VENDA')['DIVERGE'].agg(['sum', 'size']))

       ID_TRANSACAO DATA_HORA_VENDA PDV_CAIXA  OPERADOR  COD_PRODUTO  \
0            900001      2026-01-01   CAIXA_P   JULIANA          503
1            900002      2026-01-01  CAIXA_02  PATRICIA      1000001
2            900003      2026-01-01  CAIXA_02  PATRICIA          404
3            900004      2026-01-01  CAIXA_02  PATRICIA          303
4            900005      2026-01-01  CAIXA_02  PATRICIA          304
...             ...             ...       ...       ...          ...
15817        915818      31/03/2026  CAIXA_01   JULIANA          501
15818        915819      31/03/2026  CAIXA_01   JULIANA          301
15819        915820      31/03/2026  CAIXA_02  PATRICIA      1000001
15820        915821      31/03/2026  CAIXA_02  PATRICIA      1000001
15821        915822      31/03/2026  CAIXA_01   JULIANA          503

       QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO      FORMA_PAGTO  \
0                5                3.94       19.70  FIADO_CADERNETO
1                2               34.47       68.94  FIADO_CADERNETO
2                4               32.32      129.28  FIADO_CADERNETO
3                4               36.05      144.20      CARTAO_CRED
4                5               25.25      126.25       CARTAO_DEB
...            ...                 ...         ...              ...
15817            2                8.27       16.54      CARTAO_CRED
15818            4               28.53      114.12              PIX
15819            1                0.00        0.00       CARTAO_DEB
15820            5               21.13      105.65            MISTO
15821            3               21.69       65.07       CARTAO_DEB

      STATUS_VENDA  MES   ANO  VENDAS_TOTAL  DIF_VENDA  DIVERGE
0        CONCLUIDA    1  2026         19.70        0.0    False
1        CONCLUIDA    1  2026         68.94        0.0    False
2        CONCLUIDA    1  2026        129.28        0.0    False
3        CONCLUIDA    1  2026        144.20        0.0    False
4        CONCLUIDA    1  2026        126.25        0.0    False
...            ...  ...   ...           ...        ...      ...
15817    CONCLUIDA    3  2026         16.54        0.0    False
15818    CONCLUIDA    3  2026        114.12        0.0    False
15819    CANCELADA    3  2026          0.00        0.0    False
15820    CONCLUIDA    3  2026        105.65        0.0    False
15821    CONCLUIDA    3  2026         65.07        0.0    False

[15822 rows x 15 columns]
               sum  size
STATUS_VENDA
ABERTO        2247  2247
CANCELADA        0  2226
CONCLUIDA        0  9051
ESTORNADA     2298  2298