## Inicializa o principais dependencias

In [2]:
%run "../0 - Base/inicializa.ipynb"

In [3]:
GoldVendas = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\Mercado\\2 - Silver\\silverVendas_ETL.csv")

In [4]:
GoldVendas.head(10)

,ID_TRANSACAO,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA,DATA,MES,ANO
0,900001,CAIXA_P,JULIANA,503.0,5.0,3.94,19.70,FIADO_CADERNETO,CONCLUIDA,2026-01-01,1,2026
1,900002,CAIXA_02,PATRICIA,0.0,2.0,34.47,68.94,FIADO_CADERNETO,CONCLUIDA,2026-01-01,1,2026
2,900003,CAIXA_02,PATRICIA,404.0,4.0,32.32,129.28,FIADO_CADERNETO,CONCLUIDA,2026-01-01,1,2026
3,900004,CAIXA_02,PATRICIA,303.0,4.0,36.05,144.20,CARTAO_CRED,CONCLUIDA,2026-01-01,1,2026
4,900005,CAIXA_02,PATRICIA,304.0,5.0,25.25,126.25,CARTAO_DEB,CONCLUIDA,2026-01-01,1,2026
5,900006,CAIXA_02,PATRICIA,503.0,1.0,41.68,41.68,NaN,CONCLUIDA,2026-01-01,1,2026
6,900007,CAIXA_01,JULIANA,402.0,4.0,10.36,0.00,MISTO,ABERTO,2026-01-01,1,2026
7,900008,CAIXA_P,JULIANA,101.0,3.0,33.87,0.00,PIX,ABERTO,2026-01-01,1,2026
8,900009,CAIXA_P,JULIANA,103.0,2.0,30.00,0.00,MISTO,ESTORNADA,2026-01-01,1,2026
9,900010,CAIXA_P,JULIANA,401.0,2.0,6.50,13.00,FIADO_CADERNETO,CONCLUIDA,2026-01-01,1,2026

In [63]:
GoldVendas['COD_PRODUTO'].value_counts()

COD_PRODUTO
0.0      1306
102.0     684
403.0     680
302.0     672
104.0     667
201.0     661
105.0     659
401.0     650
501.0     645
999.0     643
103.0     632
301.0     631
303.0     627
101.0     623
202.0     620
203.0     619
503.0     614
502.0     608
304.0     607
204.0     606
601.0     602
602.0     601
402.0     600
404.0     565
Name: count, dtype: int64

-------

# CRIA NOVAS TABELAS

### Agrupa por ID

In [5]:
g_id_qtd = (
    GoldVendas
    .groupby('ID_TRANSACAO', as_index=False)['QTD_VENDIDA']
    .sum()
)
g_id_qtd.head(3)

   ID_TRANSACAO  QTD_VENDIDA
0        900001          5.0
1        900002          2.0
2        900003          4.0

In [6]:
g_id_unit = (
    GoldVendas
    .groupby('ID_TRANSACAO', as_index=False)['PRECO_UNIT_COBRADO']
    .sum()
)
g_id_unit.head(3)

   ID_TRANSACAO  PRECO_UNIT_COBRADO
0        900001                3.94
1        900002               34.47
2        900003               32.32

In [7]:
g_id_total = (
    GoldVendas
    .groupby('ID_TRANSACAO', as_index=False)['TOTAL_PAGO']
    .sum()
)
g_id_total.head(3)

   ID_TRANSACAO  TOTAL_PAGO
0        900001       19.70
1        900002       68.94
2        900003      129.28

In [8]:
g_id = pd.concat(
    [g_id_qtd['ID_TRANSACAO'], g_id_qtd['QTD_VENDIDA'], g_id_unit['PRECO_UNIT_COBRADO'], g_id_total['TOTAL_PAGO']],
    axis=1
)
g_id.head(3)

   ID_TRANSACAO  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0        900001          5.0                3.94       19.70
1        900002          2.0               34.47       68.94
2        900003          4.0               32.32      129.28

-------

### Agrupa por Caixa

In [9]:
g_cx_qtd = (
    GoldVendas
    .groupby('PDV_CAIXA', as_index=False)['QTD_VENDIDA']
    .sum()
)
g_cx_qtd.head(3)

  PDV_CAIXA  QTD_VENDIDA
0  CAIXA_01      18793.0
1  CAIXA_02      19042.0
2   CAIXA_P       9589.0

In [10]:
g_cx_unit = (
    GoldVendas
    .groupby('PDV_CAIXA', as_index=False)['PRECO_UNIT_COBRADO']
    .sum()
)
g_cx_unit.head(3)

  PDV_CAIXA  PRECO_UNIT_COBRADO
0  CAIXA_01           126367.41
1  CAIXA_02           128519.87
2   CAIXA_P            64255.47

In [11]:
g_cx_total = (
    GoldVendas
    .groupby('PDV_CAIXA', as_index=False)['TOTAL_PAGO']
    .sum()
)
g_cx_total.head(3)

  PDV_CAIXA  TOTAL_PAGO
0  CAIXA_01   253815.99
1  CAIXA_02   262752.77
2   CAIXA_P   128483.58

In [12]:
g_caixa = pd.concat(
    [g_cx_qtd['PDV_CAIXA'], g_cx_qtd['QTD_VENDIDA'], g_cx_unit['PRECO_UNIT_COBRADO'], g_cx_total['TOTAL_PAGO']],
    axis=1
)
g_caixa.head(3)

  PDV_CAIXA  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0  CAIXA_01      18793.0           126367.41   253815.99
1  CAIXA_02      19042.0           128519.87   262752.77
2   CAIXA_P       9589.0            64255.47   128483.58

----

### Operdor

In [13]:
g_op_qtd = (
    GoldVendas
    .groupby('OPERADOR', as_index=False)['QTD_VENDIDA']
    .sum()
)
g_op_qtd.head(3)

           OPERADOR  QTD_VENDIDA
0  CARLOS (GERENTE)        933.0
1           JULIANA      26862.0
2    N_IDENTIFICADO        849.0

In [14]:
g_op_unit = (
    GoldVendas
    .groupby('OPERADOR', as_index=False)['PRECO_UNIT_COBRADO']
    .sum()
)
g_op_unit.head(3)

           OPERADOR  PRECO_UNIT_COBRADO
0  CARLOS (GERENTE)             6326.49
1           JULIANA           180505.69
2    N_IDENTIFICADO             5594.18

In [15]:
g_op_total = (
    GoldVendas
    .groupby('OPERADOR', as_index=False)['TOTAL_PAGO']
    .sum()
)
g_op_total.head(3)

           OPERADOR  TOTAL_PAGO
0  CARLOS (GERENTE)    12033.08
1           JULIANA   362366.23
2    N_IDENTIFICADO    10741.34

In [16]:
g_operador = pd.concat(
    [g_op_qtd['OPERADOR'], g_op_qtd['QTD_VENDIDA'], g_op_unit['PRECO_UNIT_COBRADO'], g_op_total['TOTAL_PAGO']],
    axis=1
)
g_operador.head(3)

           OPERADOR  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0  CARLOS (GERENTE)        933.0             6326.49    12033.08
1           JULIANA      26862.0           180505.69   362366.23
2    N_IDENTIFICADO        849.0             5594.18    10741.34

----

### Cod_Produto

In [17]:
g_cod_qtd = (
    GoldVendas
    .groupby('COD_PRODUTO', as_index=False)['QTD_VENDIDA']
    .sum()
)
g_cod_qtd.head(3)

   COD_PRODUTO  QTD_VENDIDA
0          0.0       3933.0
1        101.0       1890.0
2        102.0       2067.0

In [18]:
g_cod_unit = (
    GoldVendas
    .groupby('OPERADOR', as_index=False)['PRECO_UNIT_COBRADO']
    .sum()
)
g_cod_unit.head(3)

           OPERADOR  PRECO_UNIT_COBRADO
0  CARLOS (GERENTE)             6326.49
1           JULIANA           180505.69
2    N_IDENTIFICADO             5594.18

In [19]:
g_cod_total = (
    GoldVendas
    .groupby('COD_PRODUTO', as_index=False)['TOTAL_PAGO']
    .sum()
)
g_cod_total.head(3)

   COD_PRODUTO  TOTAL_PAGO
0          0.0    49226.59
1        101.0    25935.86
2        102.0    29890.43

In [20]:
g_cod = pd.concat(
    [g_cod_qtd['COD_PRODUTO'], g_cod_qtd['QTD_VENDIDA'], g_cod_unit['PRECO_UNIT_COBRADO'], g_cod_total['TOTAL_PAGO']],
    axis=1
)
g_cod.head(3)

   COD_PRODUTO  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0          0.0       3933.0             6326.49    49226.59
1        101.0       1890.0           180505.69    25935.86
2        102.0       2067.0             5594.18    29890.43

----

### Forma pag

In [21]:
g_fpagamento_qtd = (
    GoldVendas
    .groupby('FORMA_PAGTO', as_index=False)['QTD_VENDIDA']
    .sum()
)
g_fpagamento_qtd.head(3)

   FORMA_PAGTO  QTD_VENDIDA
0  CARTAO_CRED       5819.0
1   CARTAO_DEB       6143.0
2     DINHEIRO       5833.0

In [22]:
g_fpagamento_unit = (
    GoldVendas
    .groupby('FORMA_PAGTO', as_index=False)['PRECO_UNIT_COBRADO']
    .sum()
)
g_fpagamento_unit.head(3)

   FORMA_PAGTO  PRECO_UNIT_COBRADO
0  CARTAO_CRED            38718.84
1   CARTAO_DEB            40931.62
2     DINHEIRO            39611.40

In [23]:
g_fpagamento_total = (
    GoldVendas
    .groupby('FORMA_PAGTO', as_index=False)['TOTAL_PAGO']
    .sum()
)
g_fpagamento_total.head(3)

   FORMA_PAGTO  TOTAL_PAGO
0  CARTAO_CRED    77933.86
1   CARTAO_DEB    84828.50
2     DINHEIRO    77372.83

In [24]:
g_forma_pagamento = pd.concat(
    [g_fpagamento_qtd['FORMA_PAGTO'], g_fpagamento_qtd['QTD_VENDIDA'], g_fpagamento_unit['PRECO_UNIT_COBRADO'], g_fpagamento_total['TOTAL_PAGO']],
    axis=1
)
g_forma_pagamento.head(3)

   FORMA_PAGTO  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0  CARTAO_CRED       5819.0            38718.84    77933.86
1   CARTAO_DEB       6143.0            40931.62    84828.50
2     DINHEIRO       5833.0            39611.40    77372.83

----

### Status

In [25]:
g_status_qtd = (
    GoldVendas
    .groupby('STATUS_VENDA', as_index=False)['QTD_VENDIDA']
    .sum()
)
g_status_qtd.head(3)

  STATUS_VENDA  QTD_VENDIDA
0       ABERTO       6748.0
1    CANCELADA       6525.0
2    CONCLUIDA      27302.0

In [27]:
g_status_unit = (
    GoldVendas
    .groupby('STATUS_VENDA', as_index=False)['PRECO_UNIT_COBRADO']
    .sum()
)
g_status_unit.head(3)

  STATUS_VENDA  PRECO_UNIT_COBRADO
0       ABERTO            52637.00
1    CANCELADA                0.00
2    CONCLUIDA           212733.18

In [28]:
g_status_total = (
    GoldVendas
    .groupby('STATUS_VENDA', as_index=False)['TOTAL_PAGO']
    .sum()
)
g_status_total.head(3)

  STATUS_VENDA  TOTAL_PAGO
0       ABERTO        0.00
1    CANCELADA        0.00
2    CONCLUIDA   645052.34

In [29]:
g_status = pd.concat(
    [g_status_qtd['STATUS_VENDA'], g_status_qtd['QTD_VENDIDA'], g_status_unit['PRECO_UNIT_COBRADO'], g_status_total['TOTAL_PAGO']],
    axis=1
)
g_status.head(3)

  STATUS_VENDA  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0       ABERTO       6748.0            52637.00        0.00
1    CANCELADA       6525.0                0.00        0.00
2    CONCLUIDA      27302.0           212733.18   645052.34

----

### Ano

In [30]:
g_ano_qtd = (
    GoldVendas
    .groupby('ANO', as_index=False)['QTD_VENDIDA']
    .sum()
)
g_ano_qtd.head(3)

    ANO  QTD_VENDIDA
0  2026      47424.0

In [31]:
g_ano_unit = (
    GoldVendas
    .groupby('ANO', as_index=False)['PRECO_UNIT_COBRADO']
    .sum()
)
g_ano_unit.head(3)

    ANO  PRECO_UNIT_COBRADO
0  2026           319142.75

In [32]:
g_ano_total = (
    GoldVendas
    .groupby('ANO', as_index=False)['TOTAL_PAGO']
    .sum()
)
g_ano_total.head(3)

    ANO  TOTAL_PAGO
0  2026   645052.34

In [33]:
g_ano = pd.concat(
    [g_ano_qtd['ANO'], g_ano_qtd['QTD_VENDIDA'], g_ano_unit['PRECO_UNIT_COBRADO'], g_ano_total['TOTAL_PAGO']],
    axis=1
)
g_ano.head(3)

    ANO  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0  2026      47424.0           319142.75   645052.34

----

### Mes

In [34]:
g_mes_qtd = (
    GoldVendas
    .groupby('MES', as_index=False)['QTD_VENDIDA']
    .sum()
)
g_mes_qtd.head(3)

   MES  QTD_VENDIDA
0    1      13150.0
1    2      11394.0
2    3      13656.0

In [35]:
g_mes_unit = (
    GoldVendas
    .groupby('MES', as_index=False)['PRECO_UNIT_COBRADO']
    .sum()
)
g_mes_unit.head(3)

   MES  PRECO_UNIT_COBRADO
0    1            88762.04
1    2            76773.02
2    3            92865.81

In [36]:
g_mes_total = (
    GoldVendas
    .groupby('MES', as_index=False)['TOTAL_PAGO']
    .sum()
)
g_mes_total.head(3)

   MES  TOTAL_PAGO
0    1   177091.79
1    2   154554.71
2    3   188314.40

In [37]:
g_mes = pd.concat(
    [g_mes_qtd['MES'], g_mes_qtd['QTD_VENDIDA'], g_mes_unit['PRECO_UNIT_COBRADO'], g_mes_total['TOTAL_PAGO']],
    axis=1
)
g_mes.head(3)

   MES  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0    1      13150.0            88762.04   177091.79
1    2      11394.0            76773.02   154554.71
2    3      13656.0            92865.81   188314.40

----

## Test

In [38]:
g_test_qtd = (
    GoldVendas
    .groupby('OPERADOR', as_index=False)['ID_TRANSACAO']
    .sum()
)
g_test_qtd.head(10)

           OPERADOR  ID_TRANSACAO
0  CARLOS (GERENTE)     280510519
1           JULIANA    8125314984
2    N_IDENTIFICADO     257931850
3          PATRICIA    5458946261

In [50]:
g_test_qtd = (
    GoldVendas
    .groupby('COD_PRODUTO', as_index=False)['ID_TRANSACAO']
    .count()
)

g_test_qtd.head(5)

   COD_PRODUTO  ID_TRANSACAO
0          0.0          1306
1        101.0           623
2        102.0           684
3        103.0           632
4        104.0           667

In [51]:
g_test_qtd = (
    GoldVendas
    .groupby('FORMA_PAGTO', as_index=False)['PDV_CAIXA']
    .count()
)

g_test_qtd.head(5)

       FORMA_PAGTO  PDV_CAIXA
0      CARTAO_CRED       1921
1       CARTAO_DEB       2018
2         DINHEIRO       1942
3  FIADO_CADERNETO       2062
4            MISTO       1991

In [52]:
g_test_qtd = (
    GoldVendas
    .groupby('STATUS_VENDA', as_index=False)['COD_PRODUTO']
    .count()
)

g_test_qtd.head(5)

  STATUS_VENDA  COD_PRODUTO
0       ABERTO         2247
1    CANCELADA         2226
2    CONCLUIDA         9051
3    ESTORNADA         2298

In [53]:
g_test_qtd = (
    GoldVendas
    .groupby('STATUS_VENDA', as_index=False)['PRECO_UNIT_COBRADO']
    .sum()
    .rank()
)

g_test_qtd.head(10)

   STATUS_VENDA  PRECO_UNIT_COBRADO
0           1.0                 2.0
1           2.0                 1.0
2           3.0                 4.0
3           4.0                 3.0

In [54]:
g_test1_qtd = (
    GoldVendas
    .groupby('OPERADOR')
    .agg(
    TOTAL=('TOTAL_PAGO', 'sum'),
    MEDIA=('TOTAL_PAGO', 'mean'),
    QUANTIDADE=('QTD_VENDIDA', 'count'),
    COD_PRODUTOS=('ID_TRANSACAO', 'nunique')
)
)

g_test1_qtd.head(10)

                      TOTAL      MEDIA  QUANTIDADE  COD_PRODUTOS
OPERADOR
CARLOS (GERENTE)   12033.08  38.942006         309           309
JULIANA           362366.23  40.487847        8950          8950
N_IDENTIFICADO     10741.34  37.821620         284           284
PATRICIA          249150.73  41.442237        6012          6012

# Resumo Tabelas

In [55]:
g_id.head(3)

   ID_TRANSACAO  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0        900001          5.0                3.94       19.70
1        900002          2.0               34.47       68.94
2        900003          4.0               32.32      129.28

In [56]:
g_caixa.head(3)

  PDV_CAIXA  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0  CAIXA_01      18793.0           126367.41   253815.99
1  CAIXA_02      19042.0           128519.87   262752.77
2   CAIXA_P       9589.0            64255.47   128483.58

In [57]:
g_operador.head(3)

           OPERADOR  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0  CARLOS (GERENTE)        933.0             6326.49    12033.08
1           JULIANA      26862.0           180505.69   362366.23
2    N_IDENTIFICADO        849.0             5594.18    10741.34

In [58]:
g_cod.head(3)

   COD_PRODUTO  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0          0.0       3933.0             6326.49    49226.59
1        101.0       1890.0           180505.69    25935.86
2        102.0       2067.0             5594.18    29890.43

In [59]:
g_forma_pagamento.head(3)

   FORMA_PAGTO  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0  CARTAO_CRED       5819.0            38718.84    77933.86
1   CARTAO_DEB       6143.0            40931.62    84828.50
2     DINHEIRO       5833.0            39611.40    77372.83

In [60]:
g_status.head(3)

  STATUS_VENDA  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0       ABERTO       6748.0            52637.00        0.00
1    CANCELADA       6525.0                0.00        0.00
2    CONCLUIDA      27302.0           212733.18   645052.34

In [61]:
g_ano.head(3)

    ANO  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0  2026      47424.0           319142.75   645052.34

In [49]:
g_mes.head(3)

   MES  QTD_VENDIDA  PRECO_UNIT_COBRADO  TOTAL_PAGO
0    1      13150.0            88762.04   177091.79
1    2      11394.0            76773.02   154554.71
2    3      13656.0            92865.81   188314.40