## Chama carregamentos + planilha + mostra ela

In [13]:
%run "../0 - Base/inicializa.ipynb"

In [14]:
silverPerdas = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\Mercado\\2 - Silver\\silverPerdas_ETL.csv")

In [15]:
silverPerdas.head(10)

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO,COD_PROD,QTD_AVARIADA,PREJUIZO_ESTIMADO,RESPONSAVEL,DATA,ANO,MES,V_PREJUIZO
0,01/01/2026,DEPOSITO,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,601.0,1.10,"R$ 14,18",DIEGO,2026-01-01,2026,1,14.18
1,03/01/2026,HORTI,PODRE DESCARTADO NO LIXO,601.0,6.92,"R$ 100,71",BETAO,2026-01-03,2026,1,100.71
2,04/01/2026,AÇOUGUE,LATA AMASSADA NO DESCARREGAMENTO,1000001.0,7.95,"R$ 98,53",BETAO,2026-01-04,2026,1,98.53
3,06/01/2026,CARNES,DIFERENCA DE PESO NA BALANCA,501.0,1.07,"R$ 19,3",DESCONHECIDO,2026-01-06,2026,1,19.30
4,07/01/2026,HORTI,SOBRA DE PAO DORMIDO,601.0,4.59,"R$ 158,44",DIEGO,2026-01-07,2026,1,158.44
5,10/01/2026,AÇOUGUE,QUEBRA DE CAIXA OPERADORA JULIANA,101.0,1.13,"R$ 136,15",JULIANA,2026-01-10,2026,1,136.15
6,12/01/2026,PADARIA,DIFERENCA DE PESO NA BALANCA,501.0,11.24,"R$ 64,3",CARLOS,2026-01-12,2026,1,64.30
7,14/01/2026,HORTIFRUTI,PODRE DESCARTADO NO LIXO,201.0,12.60,"R$ 155,74",DIEGO,2026-01-14,2026,1,155.74
8,17/01/2026,AÇOUGUE,PRODUTO VENCIDO NA PRATELEIRA SEM ETIQUETA,601.0,11.76,"R$ 67,76",CARLOS,2026-01-17,2026,1,67.76
9,18/01/2026,FRENTE DE CAIXA,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,101.0,8.83,"R$ 138,33",CARLOS,2026-01-18,2026,1,138.33

------

## Cria tabele Setor

In [43]:
avarias = (
    silverPerdas
    .groupby('SETOR_ORIGEM', as_index=False)['QTD_AVARIADA']
    .sum()
)

In [44]:
prejuizo = (
    silverPerdas
    .groupby('SETOR_ORIGEM', as_index=False)['V_PREJUIZO']
    .sum()
)

In [64]:
g_perdas_setor = pd.concat(
    [avarias['SETOR_ORIGEM'],avarias['QTD_AVARIADA'], prejuizo['V_PREJUIZO']],
    axis=1
)

In [65]:
g_perdas_setor.head(5)

      SETOR_ORIGEM  QTD_AVARIADA  V_PREJUIZO
0          AÇOUGUE         57.84      767.30
1           CARNES         35.53      523.24
2         DEPOSITO         75.94      957.04
3  FRENTE DE CAIXA         46.13      568.32
4            HORTI         54.98      680.75

## Cria tabele Responsável

In [70]:
Responsavel_avarias = (
    silverPerdas
    .groupby('RESPONSAVEL', as_index=False)['QTD_AVARIADA']
    .sum()
)

In [71]:
Responsavel_prejuizo = (
    silverPerdas
    .groupby('RESPONSAVEL', as_index=False)['V_PREJUIZO']
    .sum()
)

In [72]:
g_perdas_responsavel = pd.concat(
    [Responsavel_avarias['RESPONSAVEL'],Responsavel_avarias['QTD_AVARIADA'], Responsavel_prejuizo['V_PREJUIZO']],
    axis=1
)

In [74]:
g_perdas_responsavel.head(5)

    RESPONSAVEL  QTD_AVARIADA  V_PREJUIZO
0         BETAO        107.47     1501.10
1        CARLOS         72.18      931.04
2  DESCONHECIDO         93.47      790.05
3         DIEGO         60.93      888.13
4       JULIANA         37.11      630.87

-----

In [88]:
silverPerdas.head(5) #mostr tabela perdas

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO,COD_PROD,QTD_AVARIADA,PREJUIZO_ESTIMADO,RESPONSAVEL,DATA,ANO,MES,V_PREJUIZO
0,01/01/2026,DEPOSITO,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,601.0,1.10,"R$ 14,18",DIEGO,2026-01-01,2026,1,14.18
1,03/01/2026,HORTI,PODRE DESCARTADO NO LIXO,601.0,6.92,"R$ 100,71",BETAO,2026-01-03,2026,1,100.71
2,04/01/2026,AÇOUGUE,LATA AMASSADA NO DESCARREGAMENTO,1000001.0,7.95,"R$ 98,53",BETAO,2026-01-04,2026,1,98.53
3,06/01/2026,CARNES,DIFERENCA DE PESO NA BALANCA,501.0,1.07,"R$ 19,3",DESCONHECIDO,2026-01-06,2026,1,19.30
4,07/01/2026,HORTI,SOBRA DE PAO DORMIDO,601.0,4.59,"R$ 158,44",DIEGO,2026-01-07,2026,1,158.44

## Cria tabele ANO

In [91]:
ano_avarias = (
    silverPerdas
    .groupby('ANO', as_index=False)['QTD_AVARIADA']
    .sum()
)

In [92]:
ano_prejuizo = (
    silverPerdas
    .groupby('ANO', as_index=False)['V_PREJUIZO']
    .sum()
)

In [93]:
g_perdas_Ano = pd.concat(
    [ano_avarias['ANO'],ano_avarias['QTD_AVARIADA'],ano_prejuizo['V_PREJUIZO']],
    axis=1
)

In [94]:
g_perdas_Ano.head(5)

    ANO  QTD_AVARIADA  V_PREJUIZO
0  2026        371.16     4741.19

-------------

## Cria tabele MES

In [100]:
mes_avarias = (
    silverPerdas
    .groupby('MES', as_index=False)['QTD_AVARIADA']
    .sum()
)

In [97]:
mes_prejuizo = (
    silverPerdas
    .groupby('MES', as_index=False)['V_PREJUIZO']
    .sum()
)

In [98]:
g_perdas_mes = pd.concat(
    [mes_avarias['MES'],mes_avarias['QTD_AVARIADA'],mes_prejuizo['V_PREJUIZO']],
    axis=1
)

In [99]:
g_perdas_mes.head(5)

   MES  QTD_AVARIADA  V_PREJUIZO
0    1        135.85     1767.28
1    2         89.68     1286.58
2    3        145.63     1687.33

------

## Cria tabele COD_PROD

In [109]:
cod_avarias = (
    silverPerdas
    .groupby('COD_PROD', as_index=False)['QTD_AVARIADA']
    .sum()
)

In [106]:
cod_prejuizo = (
    silverPerdas
    .groupby('COD_PROD', as_index=False)['V_PREJUIZO']
    .sum()
)

In [107]:
g_perdas_cod = pd.concat(
    [cod_avarias['COD_PROD'],cod_avarias['QTD_AVARIADA'],cod_prejuizo['V_PREJUIZO']],
    axis=1
)

In [108]:
g_perdas_cod.head(5)

   COD_PROD  QTD_AVARIADA  V_PREJUIZO
0     101.0         44.95      661.74
1     102.0         15.99      233.96
2     201.0         48.96      623.04
3     301.0         25.02      255.31
4     501.0         22.82      191.65

-------

# RESUMO TABELAS

In [112]:
g_perdas_setor.head(5)

      SETOR_ORIGEM  QTD_AVARIADA  V_PREJUIZO
0          AÇOUGUE         57.84      767.30
1           CARNES         35.53      523.24
2         DEPOSITO         75.94      957.04
3  FRENTE DE CAIXA         46.13      568.32
4            HORTI         54.98      680.75

In [113]:
g_perdas_responsavel.head(5)

    RESPONSAVEL  QTD_AVARIADA  V_PREJUIZO
0         BETAO        107.47     1501.10
1        CARLOS         72.18      931.04
2  DESCONHECIDO         93.47      790.05
3         DIEGO         60.93      888.13
4       JULIANA         37.11      630.87

In [114]:
g_perdas_Ano.head(5)

    ANO  QTD_AVARIADA  V_PREJUIZO
0  2026        371.16     4741.19

In [115]:
g_perdas_mes.head(5)

   MES  QTD_AVARIADA  V_PREJUIZO
0    1        135.85     1767.28
1    2         89.68     1286.58
2    3        145.63     1687.33

In [116]:
g_perdas_cod.head(5)

   COD_PROD  QTD_AVARIADA  V_PREJUIZO
0     101.0         44.95      661.74
1     102.0         15.99      233.96
2     201.0         48.96      623.04
3     301.0         25.02      255.31
4     501.0         22.82      191.65