In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
silverCompras = pd.read_excel("..\\Raw\\table_silver\\silverCompras_ETL.xlsx")

In [3]:
silverCompras.head(10)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO,N_NF,TOTAL_NOTA,DATA,MES,ANO,DIA,ID_FORNECEDOR,PRECO_UNIT
0,NF-1006,01/01/2026,CEASA SP,101,55,163.39,MATEUS,1006,163.39,2026-01-01,1,2026,1,1001,2.97
1,NF-1046,01/01/2026,CEASA SP,102,119,335.78,THIAGO,1046,335.78,2026-01-01,1,2026,1,1001,2.82
2,NF-1018,01/01/2026,CEASA SP,103,115,243.92,THIAGO,1018,243.92,2026-01-01,1,2026,1,1001,2.12
3,NF-1013,01/01/2026,CEASA SP,104,41,123.78,DIEGO,1013,123.78,2026-01-01,1,2026,1,1001,3.02
4,NF-1004,01/01/2026,CEASA SP,105,85,235.48,DIEGO,1004,235.48,2026-01-01,1,2026,1,1001,2.77
5,NF-5009,02/01/2026,FRIGORIFICO FRIBOI,201,55,1514.03,MATEUS,5009,1514.03,2026-01-02,1,2026,2,1002,27.53
6,NF-5018,02/01/2026,FRIGORIFICO FRIBOI,202,29,1063.28,MARCIO,5018,1063.28,2026-01-02,1,2026,2,1002,36.66
7,NF-5011,02/01/2026,FRIGORIFICO FRIBOI,203,21,753.7,MARCIO,5011,753.70,2026-01-02,1,2026,2,1002,35.89
8,NF-5012,02/01/2026,FRIGORIFICO FRIBOI,204,49,1195.59,MATEUS,5012,1195.59,2026-01-02,1,2026,2,1002,24.40
9,NF-1031,03/01/2026,CEASA SP,101,54,178.21,MATEUS,1031,178.21,2026-01-03,1,2026,3,1001,3.30

-----

# Cria tabela de agrupamento por coluna

### cria fornecedor

In [4]:
gold_fornecedor = silverCompras.groupby('FORNECEDOR', as_index=False).agg(
      QTD_COMPRADA=('QTD_COMPRADA', 'sum'),
      TOTAL_NOTA=('TOTAL_NOTA', 'sum'),
  )
gold_fornecedor.head(5)

           FORNECEDOR  QTD_COMPRADA  TOTAL_NOTA
0            CEASA SP         18133    53811.60
1  FRIGORIFICO FRIBOI          6202   168446.25

## Cria Cod_Prod

In [5]:
gold_cod_qtd = silverCompras.groupby('COD_PROD', as_index=False).agg(
    QTD_COMPRADA=('QTD_COMPRADA', 'sum'),
    TOTAL_NOTA=('TOTAL_NOTA', 'sum'),
)
gold_cod_qtd.head(5)

   COD_PROD  QTD_COMPRADA  TOTAL_NOTA
0       101          3946    11203.90
1       102          3180    11282.03
2       103          3762    10629.73
3       104          3388     9430.10
4       105          3857    11265.84

### Cria Responsável

In [6]:
gold_resp = silverCompras.groupby('RESPONSAVEL_RECEBIMENTO', as_index=False).agg(
    QTD_COMPRADA = ('QTD_COMPRADA', 'sum'),
    TOTAL_NOTA = ('TOTAL_NOTA','sum'),
)
gold_resp.head(5)

  RESPONSAVEL_RECEBIMENTO  QTD_COMPRADA  TOTAL_NOTA
0                   BETAO          1540    43048.11
1                   DIEGO          6397    19081.07
2              DIEGO LIMA          2000     5883.50
3                  MARCIO          1270    36124.02
4                  MATEUS          4199    55742.19

### Cria mes

In [7]:
gold_mes = silverCompras.groupby('MES', as_index=False).agg(
    QTD_COMPRADA = ('QTD_COMPRADA', 'sum'),
    TOTAL_NOTA = ('TOTAL_NOTA','sum'),
)
gold_mes.head(5)

   MES  QTD_COMPRADA  TOTAL_NOTA
0    1          8093    73840.64
1    2          7746    71811.98
2    3          8496    76605.23

### Cria por ano

In [8]:
gold_ano = silverCompras.groupby('ANO', as_index=False).agg(
    QTD_COMPRADA = ('QTD_COMPRADA', 'sum'),
    TOTAL_NOTA = ('TOTAL_NOTA','sum'),
)
gold_ano.head(5)

    ANO  QTD_COMPRADA  TOTAL_NOTA
0  2026         24335   222257.85

------

## Pela N_NF

In [9]:
gold_nf = silverCompras.groupby('N_NF', as_index=False).agg(
    QTD_COMPRADA = ('QTD_COMPRADA', 'sum'),
    TOTAL_NOTA = ('TOTAL_NOTA','sum'),
)
gold_nf.head(5)

   N_NF  QTD_COMPRADA  TOTAL_NOTA
0  1000           136      405.35
1  1001           373     1102.72
2  1002            91      197.82
3  1003           275     1242.49
4  1004           398      942.15

----------

## RESUMO TABELAS

In [10]:
gold_fornecedor.head(5)

           FORNECEDOR  QTD_COMPRADA  TOTAL_NOTA
0            CEASA SP         18133    53811.60
1  FRIGORIFICO FRIBOI          6202   168446.25

In [11]:
gold_cod_qtd.head(5)

   COD_PROD  QTD_COMPRADA  TOTAL_NOTA
0       101          3946    11203.90
1       102          3180    11282.03
2       103          3762    10629.73
3       104          3388     9430.10
4       105          3857    11265.84

In [12]:
gold_resp.head(5)

  RESPONSAVEL_RECEBIMENTO  QTD_COMPRADA  TOTAL_NOTA
0                   BETAO          1540    43048.11
1                   DIEGO          6397    19081.07
2              DIEGO LIMA          2000     5883.50
3                  MARCIO          1270    36124.02
4                  MATEUS          4199    55742.19

In [13]:
gold_mes.head(5)

   MES  QTD_COMPRADA  TOTAL_NOTA
0    1          8093    73840.64
1    2          7746    71811.98
2    3          8496    76605.23

In [14]:
gold_ano.head(5)

    ANO  QTD_COMPRADA  TOTAL_NOTA
0  2026         24335   222257.85

In [15]:
gold_nf.head(5)

   N_NF  QTD_COMPRADA  TOTAL_NOTA
0  1000           136      405.35
1  1001           373     1102.72
2  1002            91      197.82
3  1003           275     1242.49
4  1004           398      942.15

-----

In [26]:
resultado = False

In [27]:
gold_Compras = silverCompras

def export_dados_excel(resultado):

    pasta = Path("..\\Raw\\table_gold\\")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "gold_Compras.xlsx"

        # 1. Criar os arquivos
        gold_Compras.to_excel(arquivo_excel, index=False)


        # 3. Consolidar em um Excel com duas abas
        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            gold_Compras.to_excel(
                writer,
                sheet_name="g_compras",
                index=False
            )

            gold_fornecedor.to_excel(
                writer,
                sheet_name="fornecedor",
                index=False
            )


            gold_cod_qtd.to_excel(
                writer,
                sheet_name="cod_prod",
                index=False
            )

            gold_resp.to_excel(
                writer,
                sheet_name="resposavel",
                index=False
            )

            gold_mes.to_excel(
                writer,
                sheet_name="mes",
                index=False
            )

            gold_ano.to_excel(
                writer,
                sheet_name="ano",
                index=False
            )

            gold_nf.to_excel(
                writer,
                sheet_name="nf",
                index=False
            )

            
        return True

    print("ERRO")
    return False

In [28]:
export_dados_excel(True)

True