In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
silverCadadastro = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\Mercado\\2 - Silver\\SilverCadastro_ETL.csv")

-----

# MEDIDAS planilha Cadastro ETL

In [3]:
silverCadadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA,MARGEM,PROD,MEDIDA,UNIDADE
0,101,HORTIFRUTI,TOMATE DEBORA KG,7.9,3.2,4.7,TOMATE DEBORA,1,KG
1,102,HORTIFRUTI,BANANA PRATA KG,5.5,2.1,3.4,BANANA PRATA,1,KG
2,103,HORTIFRUTI,ALFACE AMERICANA UN,3.5,1.2,2.3,ALFACE AMERICANA,1,UN
3,104,HORTIFRUTI,BATATA MONALISA KG,5.9,2.5,3.4,BATATA MONALISA,1,KG
4,105,HORTIFRUTI,CEBOLA NACIONAL KG,0.0,2.8,-2.8,CEBOLA NACIONA,1,L
5,201,ACOUGUE,PICANHA BOV RESFRIADA KG,79.9,42.0,37.9,PICANHA BOV RESFRIADA,1,KG
6,202,ACOUGUE,ALCATRA C/ MAMINHA KG,44.9,26.0,18.9,ALCATRA C/ MAMINHA,1,KG
7,203,ACOUGUE,CARNE MOIDA DE 2A KG,29.9,14.0,15.9,CARNE MOIDA DE 2A,1,KG
8,204,ACOUGUE,LINGUICA TOSCANA KG,22.9,12.0,10.9,LINGUICA TOSCANA,1,KG
9,204,ACOUGUE,LINGUICA TOSCANA KG,22.9,12.0,10.9,LINGUICA TOSCANA,1,KG

In [4]:
silverCadadastro['COD_PROD'].value_counts()

COD_PROD
204    2
101    1
102    1
103    1
104    1
105    1
201    1
202    1
203    1
301    1
302    1
303    1
304    1
401    1
402    1
403    1
404    1
501    1
502    1
503    1
601    1
602    1
Name: count, dtype: int64

In [5]:
silverCadadastro.columns

Index(['COD_PROD', 'CATEGORIA_BRUTA', 'NOME_PRODUTO', 'VENDA_CADASTRO',
       'CUSTO_VENDA', 'MARGEM', 'PROD', 'MEDIDA', 'UNIDADE'],
      dtype='str')

In [6]:
silverCadadastro.shape

(23, 9)

------

## Cria tabelas com dados agrupados

In [7]:
gold_Cadastro = silverCadadastro # criar uma nova tabela com dados importados

In [8]:
#cria uma tabelas com dados categoria x vendas
gold_s_venda = (
    gold_Cadastro
    .groupby('CATEGORIA_BRUTA', as_index=False)['VENDA_CADASTRO']
    .sum()
)

In [9]:
#cria uma tabelas com dados categoria x custo
gold_s_custo = (
    gold_Cadastro
    .groupby('CATEGORIA_BRUTA', as_index=False)['CUSTO_VENDA']
    .sum()
)

In [10]:
#cria uma tabelas com dados categoria x margem
gold_s_margem = (
    gold_Cadastro
    .groupby('CATEGORIA_BRUTA', as_index=False)['MARGEM']
    .sum()
)

-----

In [11]:
gold_s_venda.head(5)

      CATEGORIA_BRUTA  VENDA_CADASTRO
0             ACOUGUE          200.50
1             BEBIDAS           18.28
2  FRIOS E LATICINIOS           77.09
3          HORTIFRUTI           22.80
4           MERCEARIA           16.90

In [12]:
gold_s_custo.head(5)

      CATEGORIA_BRUTA  CUSTO_VENDA
0             ACOUGUE        106.0
1             BEBIDAS         10.1
2  FRIOS E LATICINIOS         48.6
3          HORTIFRUTI         11.8
4           MERCEARIA         11.5

In [13]:
gold_s_margem.head(5)

      CATEGORIA_BRUTA  MARGEM
0             ACOUGUE   94.50
1             BEBIDAS    8.18
2  FRIOS E LATICINIOS   28.49
3          HORTIFRUTI   11.00
4           MERCEARIA    5.40

## Cria vizualizacao com dados agrupados

In [14]:
#soma os dados categoria x vendas
gold_Cadastro.groupby('CATEGORIA_BRUTA')['VENDA_CADASTRO'].sum()

CATEGORIA_BRUTA
ACOUGUE               200.50
BEBIDAS                18.28
FRIOS E LATICINIOS     77.09
HORTIFRUTI             22.80
MERCEARIA              16.90
PADARIA                28.80
SECOS E MOLHADOS       39.38
Name: VENDA_CADASTRO, dtype: float64

In [15]:
#soma os dados categoria x custo
silverCadadastro.groupby('CATEGORIA_BRUTA')['CUSTO_VENDA'].sum()

CATEGORIA_BRUTA
ACOUGUE               106.0
BEBIDAS                10.1
FRIOS E LATICINIOS     48.6
HORTIFRUTI             11.8
MERCEARIA              11.5
PADARIA                 9.5
SECOS E MOLHADOS       27.1
Name: CUSTO_VENDA, dtype: float64

In [16]:
#soma os dados categoria x margem
silverCadadastro.groupby('CATEGORIA_BRUTA')['MARGEM'].sum()

CATEGORIA_BRUTA
ACOUGUE               94.50
BEBIDAS                8.18
FRIOS E LATICINIOS    28.49
HORTIFRUTI            11.00
MERCEARIA              5.40
PADARIA               19.30
SECOS E MOLHADOS      12.28
Name: MARGEM, dtype: float64

------

In [17]:
gold_s_venda.head(3) # motra tabela suma vendas

      CATEGORIA_BRUTA  VENDA_CADASTRO
0             ACOUGUE          200.50
1             BEBIDAS           18.28
2  FRIOS E LATICINIOS           77.09

In [18]:
gold_s_custo.head(3)

      CATEGORIA_BRUTA  CUSTO_VENDA
0             ACOUGUE        106.0
1             BEBIDAS         10.1
2  FRIOS E LATICINIOS         48.6

In [19]:
gold_s_margem.head(3)

      CATEGORIA_BRUTA  MARGEM
0             ACOUGUE   94.50
1             BEBIDAS    8.18
2  FRIOS E LATICINIOS   28.49

------

## Cria 1 tabelas com dados agrupados das 3 anteriores

In [20]:
# Cria uma nova tabela com dados 3 sumatorias, horizontal
CategoriaVendas = pd.concat(
    [gold_s_venda, gold_s_custo, gold_s_margem],
    axis=1
)

In [21]:
# Cria uma nova tabela com dados 3 sumatorias, contatenando na vertical
CategoriaVendas_2 = pd.concat(
    [gold_s_venda, gold_s_custo, gold_s_margem],
    ignore_index=True
)

In [22]:
# Cria uma nova tabela com dados 3 sumatorias, deixando tabea 1 inteira, apenas resultado das outras 2
CategoriaVendas_3 = pd.concat(
    [gold_s_venda['CATEGORIA_BRUTA'], gold_s_venda['VENDA_CADASTRO'], gold_s_custo['CUSTO_VENDA'], gold_s_margem['MARGEM']],
    axis=1
)

### Erro, junto todas colunas sem padrao

In [23]:
CategoriaVendas.head(5) # Mostra a tabela Vendas

,CATEGORIA_BRUTA,VENDA_CADASTRO,CATEGORIA_BRUTA,CUSTO_VENDA,CATEGORIA_BRUTA,MARGEM
0,ACOUGUE,200.50,ACOUGUE,106.0,ACOUGUE,94.50
1,BEBIDAS,18.28,BEBIDAS,10.1,BEBIDAS,8.18
2,FRIOS E LATICINIOS,77.09,FRIOS E LATICINIOS,48.6,FRIOS E LATICINIOS,28.49
3,HORTIFRUTI,22.80,HORTIFRUTI,11.8,HORTIFRUTI,11.00
4,MERCEARIA,16.90,MERCEARIA,11.5,MERCEARIA,5.40

In [24]:
CategoriaVendas_2.head(5) # mostra a tabela 2

      CATEGORIA_BRUTA  VENDA_CADASTRO  CUSTO_VENDA  MARGEM
0             ACOUGUE          200.50          NaN     NaN
1             BEBIDAS           18.28          NaN     NaN
2  FRIOS E LATICINIOS           77.09          NaN     NaN
3          HORTIFRUTI           22.80          NaN     NaN
4           MERCEARIA           16.90          NaN     NaN

In [25]:
CategoriaVendas_3.head(30) #mostra tabela 3

      CATEGORIA_BRUTA  VENDA_CADASTRO  CUSTO_VENDA  MARGEM
0             ACOUGUE          200.50        106.0   94.50
1             BEBIDAS           18.28         10.1    8.18
2  FRIOS E LATICINIOS           77.09         48.6   28.49
3          HORTIFRUTI           22.80         11.8   11.00
4           MERCEARIA           16.90         11.5    5.40
5             PADARIA           28.80          9.5   19.30
6    SECOS E MOLHADOS           39.38         27.1   12.28

In [26]:
### FIM