## Chama carregamentos + planilha + mostra ela

In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
silverPerdas = pd.read_excel("..\\Raw\\table_silver\\silverPerdas_ETL.xlsx")

In [3]:
silverPerdas.head(10)

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO,COD_PROD,QTD_AVARIADA,PREJUIZO_ESTIMADO,RESPONSAVEL,DATA,ANO,MES,DIA,V_PREJUIZO
0,01/01/2026,DEPOSITO,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,601,1.10,"R$ 14,18",DIEGO,2026-01-01,2026,1,1,14.18
1,03/01/2026,HORTIFRUTI,PODRE DESCARTADO NO LIXO,601,6.92,"R$ 100,71",BETAO,2026-01-03,2026,1,3,100.71
2,04/01/2026,ACOUGUE,LATA AMASSADA NO DESCARREGAMENTO,1000001,7.95,"R$ 98,53",BETAO,2026-01-04,2026,1,4,98.53
3,06/01/2026,ACOUGUE,DIFERENCA DE PESO NA BALANCA,501,1.07,"R$ 19,3",DESC,2026-01-06,2026,1,6,19.30
4,07/01/2026,HORTIFRUTI,SOBRA DE PAO DORMIDO,601,4.59,"R$ 158,44",DIEGO,2026-01-07,2026,1,7,158.44
5,10/01/2026,ACOUGUE,QUEBRA DE CAIXA OPERADORA JULIANA,101,1.13,"R$ 136,15",JULIANA,2026-01-10,2026,1,10,136.15
6,12/01/2026,PADARIA,DIFERENCA DE PESO NA BALANCA,501,11.24,"R$ 64,3",CARLOS,2026-01-12,2026,1,12,64.30
7,14/01/2026,HORTIFRUTI,PODRE DESCARTADO NO LIXO,201,12.60,"R$ 155,74",DIEGO,2026-01-14,2026,1,14,155.74
8,17/01/2026,ACOUGUE,PRODUTO VENCIDO NA PRATELEIRA SEM ETIQUETA,601,11.76,"R$ 67,76",CARLOS,2026-01-17,2026,1,17,67.76
9,18/01/2026,CAIXA,FALTA DE MERCADORIA NO ESTOQUE - SUSPEITA FURTO,101,8.83,"R$ 138,33",CARLOS,2026-01-18,2026,1,18,138.33

------

## Cria tabele Setor

In [4]:
g_avarias = silverPerdas.groupby('SETOR_ORIGEM', as_index=False).agg(
    QTD_AVARIADA = ('QTD_AVARIADA', 'sum'),
    V_PREJUIZO = ('V_PREJUIZO', 'sum'),
)

In [5]:
g_avarias.head(5)

  SETOR_ORIGEM  QTD_AVARIADA  V_PREJUIZO
0      ACOUGUE         93.37     1290.54
1        CAIXA         46.13      568.32
2     DEPOSITO         75.94      957.04
3   HORTIFRUTI        119.18     1437.13
4      PADARIA         36.54      488.16

## Cria tabele Responsável

In [6]:
g_Responsavel_prejuizo = silverPerdas.groupby('RESPONSAVEL', as_index=False).agg(
    QTD_AVARIADA = ('QTD_AVARIADA', 'sum'),
    V_PREJUIZO = ('V_PREJUIZO', 'sum'),
)

In [7]:
g_Responsavel_prejuizo.head(3)

  RESPONSAVEL  QTD_AVARIADA  V_PREJUIZO
0       BETAO        107.47     1501.10
1      CARLOS         72.18      931.04
2        DESC         93.47      790.05

-----

## Cria tabele ANO

In [8]:
g_ano_prejuizo = silverPerdas.groupby('ANO', as_index=False).agg(
    QTD_AVARIADA = ('QTD_AVARIADA', 'sum'),
    V_PREJUIZO = ('V_PREJUIZO', 'sum'),
)

In [9]:
g_ano_prejuizo.head(5)

    ANO  QTD_AVARIADA  V_PREJUIZO
0  2026        371.16     4741.19

-------------

## Cria tabele MES

In [10]:
g_mes_prejuizo = silverPerdas.groupby('MES', as_index=False).agg(
    QTD_AVARIADA = ('QTD_AVARIADA', 'sum'),
    V_PREJUIZO = ('V_PREJUIZO', 'sum'),
)

In [11]:
g_mes_prejuizo.head(5)

   MES  QTD_AVARIADA  V_PREJUIZO
0    1        135.85     1767.28
1    2         89.68     1286.58
2    3        145.63     1687.33

------

## Cria tabele COD_PROD

In [12]:
g_cod_prejuizo = silverPerdas.groupby('COD_PROD', as_index=False).agg(
    QTD_AVARIADA = ('QTD_AVARIADA', 'sum'),
    V_PREJUIZO = ('V_PREJUIZO', 'sum'),
)

In [13]:
g_cod_prejuizo.head(5)

   COD_PROD  QTD_AVARIADA  V_PREJUIZO
0       101         44.95      661.74
1       102         15.99      233.96
2       201         48.96      623.04
3       301         25.02      255.31
4       501         22.82      191.65

-------

# RESUMO TABELAS

In [14]:
g_avarias.head(5)

  SETOR_ORIGEM  QTD_AVARIADA  V_PREJUIZO
0      ACOUGUE         93.37     1290.54
1        CAIXA         46.13      568.32
2     DEPOSITO         75.94      957.04
3   HORTIFRUTI        119.18     1437.13
4      PADARIA         36.54      488.16

In [15]:
g_Responsavel_prejuizo.head(5)

  RESPONSAVEL  QTD_AVARIADA  V_PREJUIZO
0       BETAO        107.47     1501.10
1      CARLOS         72.18      931.04
2        DESC         93.47      790.05
3       DIEGO         60.93      888.13
4     JULIANA         37.11      630.87

In [16]:
g_ano_prejuizo.head(5)

    ANO  QTD_AVARIADA  V_PREJUIZO
0  2026        371.16     4741.19

In [17]:
g_mes_prejuizo.head(5)

   MES  QTD_AVARIADA  V_PREJUIZO
0    1        135.85     1767.28
1    2         89.68     1286.58
2    3        145.63     1687.33

In [18]:
g_cod_prejuizo.head(5)

   COD_PROD  QTD_AVARIADA  V_PREJUIZO
0       101         44.95      661.74
1       102         15.99      233.96
2       201         48.96      623.04
3       301         25.02      255.31
4       501         22.82      191.65

-----

In [19]:
resultado = False

In [21]:
gold_Perdas = silverPerdas

def export_dados_excel(resultado):

    pasta = Path("..\\Raw\\table_gold\\")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "gold_Perdas.xlsx"

        # 1. Criar os arquivos
        gold_Perdas.to_excel(arquivo_excel, index=False)


        # 3. Consolidar em um Excel com duas abas
        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            gold_Perdas.to_excel(
                writer,
                sheet_name="g_Perdas",
                index=False
            )


            g_avarias.to_excel(
                writer,
                sheet_name="avarias",
                index=False
            )

            g_Responsavel_prejuizo.to_excel(
                writer,
                sheet_name="resposavel",
                index=False
            )

            g_mes_prejuizo.to_excel(
                writer,
                sheet_name="mes",
                index=False
            )

            g_ano_prejuizo.to_excel(
                writer,
                sheet_name="ano",
                index=False
            )

            g_cod_prejuizo.to_excel(
                writer,
                sheet_name="cod_prod",
                index=False
            )

            
        return True

    print("ERRO")
    return False

In [22]:
export_dados_excel(True)

True