In [8]:
%run "../0 - Base/inicializa.ipynb"

In [9]:
GoldComp = pd.read_csv("C:\\Users\\Public\\Teste_Jupyter\\Mercado\\2 - Silver\\silverCompras_ETL.csv")

In [10]:
GoldComp.head(10)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO,N_NF,TOTAL_NOTA,DATA,MES,ANO
0,NF-1006,01/01/2026,CEASA SP,101,55,163.39,MATEUS,1006,163.39,2026-01-01,1,2026
1,NF-1046,01/01/2026,CEASA SP,102,119,335.78,THIAGO,1046,335.78,2026-01-01,1,2026
2,NF-1018,01/01/2026,CEASA SP,103,115,243.92,THIAGO,1018,243.92,2026-01-01,1,2026
3,NF-1013,01/01/2026,CEASA SP,104,41,123.78,DIEGO,1013,123.78,2026-01-01,1,2026
4,NF-1004,01/01/2026,CEASA SP,105,85,235.48,DIEGO,1004,235.48,2026-01-01,1,2026
5,NF-5009,02/01/2026,FRIGORIFICO FRIBOI,201,55,1514.03,MATEUS,5009,1514.03,2026-01-02,1,2026
6,NF-5018,02/01/2026,FRIGORIFICO FRIBOI,202,29,1063.28,MARCIO,5018,1063.28,2026-01-02,1,2026
7,NF-5011,02/01/2026,FRIGORIFICO FRIBOI,203,21,753.7,MARCIO,5011,753.7,2026-01-02,1,2026
8,NF-5012,02/01/2026,FRIGORIFICO FRIBOI,204,49,1195.59,MATEUS,5012,1195.59,2026-01-02,1,2026
9,NF-1031,03/01/2026,CEASA SP,101,54,178.21,MATEUS,1031,178.21,2026-01-03,1,2026

-----

# Cria tabela de agrupamento por coluna

### cria fornecedor

In [63]:
gold_fornecedor_qtd = (
    GoldComp
    .groupby('FORNECEDOR', as_index=False)['QTD_COMPRADA']
    .sum()
)
gold_fornecedor_qtd.head(5)

           FORNECEDOR  QTD_COMPRADA
0            CEASA SP         18133
1  FRIGORIFICO FRIBOI          6202

In [64]:
GoldComp['TOTAL_NOTA'] = pd.to_numeric(GoldComp['TOTAL_NOTA'].astype(str).str.replace('R$ ',''))

In [65]:
gold_fornecedor_valor = (
    GoldComp
    .groupby('FORNECEDOR', as_index=False)['TOTAL_NOTA']
    .sum()
)

In [66]:
gold_fornecedor_valor.head(5)

           FORNECEDOR  TOTAL_NOTA
0            CEASA SP    53811.60
1  FRIGORIFICO FRIBOI   168446.25

In [71]:
gold_fornecedor = pd.concat(
    [gold_fornecedor_qtd['FORNECEDOR'],gold_fornecedor_qtd['QTD_COMPRADA'],gold_fornecedor_valor['TOTAL_NOTA']],
    axis=1
)
gold_fornecedor.head(3)

           FORNECEDOR  QTD_COMPRADA  TOTAL_NOTA
0            CEASA SP         18133    53811.60
1  FRIGORIFICO FRIBOI          6202   168446.25

## Cria Cod_Prod

In [76]:
gold_cod_qtd = (
    GoldComp
    .groupby('COD_PROD', as_index=False)['QTD_COMPRADA']
    .sum()
)
gold_cod_qtd.head()

   COD_PROD  QTD_COMPRADA
0       101          3946
1       102          3180
2       103          3762
3       104          3388
4       105          3857

In [83]:
gold_cod_valor = (
    GoldComp
    .groupby('COD_PROD', as_index=False)['TOTAL_NOTA']
    .sum()
)
gold_cod_valor.head()

   COD_PROD  TOTAL_NOTA
0       101    11203.90
1       102    11282.03
2       103    10629.73
3       104     9430.10
4       105    11265.84

In [82]:
gold_cod = pd.concat(
    [gold_cod_qtd['COD_PROD'],gold_cod_qtd['QTD_COMPRADA'],gold_cod_valor['TOTAL_NOTA']],
    axis=1
)
gold_cod.head(3)

   COD_PROD  QTD_COMPRADA  TOTAL_NOTA
0       101          3946    11203.90
1       102          3180    11282.03
2       103          3762    10629.73

### Cria Responsável

In [87]:
gold_resp_qtd = (
    GoldComp
    .groupby('RESPONSAVEL_RECEBIMENTO', as_index=False)['QTD_COMPRADA']
    .sum()
)
gold_resp_qtd

  RESPONSAVEL_RECEBIMENTO  QTD_COMPRADA
0                   BETAO          1540
1                   DIEGO          6397
2              DIEGO LIMA          2000
3                  MARCIO          1270
4                  MATEUS          4199
5                 ROBERTO          1613
6                  THIAGO          3865

In [89]:
gold_resp_valor = (
    GoldComp
    .groupby('RESPONSAVEL_RECEBIMENTO', as_index=False)['TOTAL_NOTA']
    .sum()
)
gold_resp_valor

  RESPONSAVEL_RECEBIMENTO  TOTAL_NOTA
0                   BETAO    43048.11
1                   DIEGO    19081.07
2              DIEGO LIMA     5883.50
3                  MARCIO    36124.02
4                  MATEUS    55742.19
5                 ROBERTO    40726.21
6                  THIAGO    10718.46

In [90]:
gold_resp = pd.concat(
    [gold_resp_qtd['RESPONSAVEL_RECEBIMENTO'],gold_resp_qtd['QTD_COMPRADA'],gold_resp_valor['TOTAL_NOTA']],
    axis=1
)
gold_resp.head(3)

  RESPONSAVEL_RECEBIMENTO  QTD_COMPRADA  TOTAL_NOTA
0                   BETAO          1540    43048.11
1                   DIEGO          6397    19081.07
2              DIEGO LIMA          2000     5883.50

### Cria mes

In [94]:
gold_mes_qtd = (
    GoldComp
    .groupby('MES', as_index=False)['QTD_COMPRADA']
    .sum()
)
gold_mes_qtd

   MES  QTD_COMPRADA
0    1          8093
1    2          7746
2    3          8496

In [95]:
gold_mes_valor= (
    GoldComp
    .groupby('MES', as_index=False)['TOTAL_NOTA']
    .sum()
)
gold_mes_valor

   MES  TOTAL_NOTA
0    1    73840.64
1    2    71811.98
2    3    76605.23

In [96]:
gold_mes = pd.concat(
    [gold_mes_qtd['MES'],gold_mes_qtd['QTD_COMPRADA'],gold_mes_valor['TOTAL_NOTA']],
    axis=1
)
gold_mes.head(3)

   MES  QTD_COMPRADA  TOTAL_NOTA
0    1          8093    73840.64
1    2          7746    71811.98
2    3          8496    76605.23

### Cria por ano

In [103]:
gold_ano_qtd = (
    GoldComp
    .groupby('ANO', as_index=False)['QTD_COMPRADA']
    .sum()
)
gold_ano_qtd

    ANO  QTD_COMPRADA
0  2026         24335

In [105]:
gold_ano_valor = (
    GoldComp
    .groupby('ANO', as_index=False)['TOTAL_NOTA']
    .sum()
)
gold_ano_valor

    ANO  TOTAL_NOTA
0  2026   222257.85

In [106]:
gold_ano = pd.concat(
    [gold_ano_qtd['ANO'],gold_ano_qtd['QTD_COMPRADA'],gold_ano_valor['TOTAL_NOTA']],
    axis=1
)
gold_ano.head(3)

    ANO  QTD_COMPRADA  TOTAL_NOTA
0  2026         24335   222257.85

------

## Pela N_NF

In [111]:
gold_nf_qtd = (
    GoldComp
    .groupby('N_NF', as_index=False)['QTD_COMPRADA']
    .sum()
)
gold_nf_qtd.head(5)

   N_NF  QTD_COMPRADA
0  1000           136
1  1001           373
2  1002            91
3  1003           275
4  1004           398

In [113]:
gold_nf_valor = (
    GoldComp
    .groupby('N_NF', as_index=False)['TOTAL_NOTA']
    .sum()
)
gold_nf_valor.head(5)

   N_NF  TOTAL_NOTA
0  1000      405.35
1  1001     1102.72
2  1002      197.82
3  1003     1242.49
4  1004      942.15

In [114]:
gold_nf = pd.concat(
    [gold_nf_qtd['N_NF'],gold_nf_qtd['QTD_COMPRADA'],gold_nf_valor['TOTAL_NOTA']],
    axis=1
)
gold_nf.head(3)

   N_NF  QTD_COMPRADA  TOTAL_NOTA
0  1000           136      405.35
1  1001           373     1102.72
2  1002            91      197.82

----------

## RESUMO TABELAS

In [115]:
gold_fornecedor.head(3)

           FORNECEDOR  QTD_COMPRADA  TOTAL_NOTA
0            CEASA SP         18133    53811.60
1  FRIGORIFICO FRIBOI          6202   168446.25

In [116]:
gold_cod.head(3)

   COD_PROD  QTD_COMPRADA  TOTAL_NOTA
0       101          3946    11203.90
1       102          3180    11282.03
2       103          3762    10629.73

In [117]:
gold_resp.head(3)

  RESPONSAVEL_RECEBIMENTO  QTD_COMPRADA  TOTAL_NOTA
0                   BETAO          1540    43048.11
1                   DIEGO          6397    19081.07
2              DIEGO LIMA          2000     5883.50

In [118]:
gold_mes.head(3)

   MES  QTD_COMPRADA  TOTAL_NOTA
0    1          8093    73840.64
1    2          7746    71811.98
2    3          8496    76605.23

In [119]:
gold_ano.head(3)

    ANO  QTD_COMPRADA  TOTAL_NOTA
0  2026         24335   222257.85

In [120]:
gold_nf.head(3)

   N_NF  QTD_COMPRADA  TOTAL_NOTA
0  1000           136      405.35
1  1001           373     1102.72
2  1002            91      197.82